version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/.github/workflows/scripts/test_report"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/docs/site"
    schedule:
      interval: "weekly"
