version: "2"
run:
  build-tags:
    - goexperiment.synctest
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - durationcheck
    - fatcontext
    - gochecksumtype
    - gocritic
    - gosmopolitan
    - nilnesserr
    - prealloc
    - reassign
    - govet
  disable:
    - testifylint
    - errchkjson #TODO: enable me
    - makezero #TODO: enable me
    - noctx #TODO: enable me
    - errorlint #TODO: enable me
    - unused #TODO: enable me
    - contextcheck
    - err113
    - exhaustive
    - gocheckcompilerdirectives
    - gosec
    - musttag
    - nilerr
    - protogetter
    - recvcheck
    - unparam
    - wrapcheck
    - sqlclosecheck # we don't use SQL
    - rowserrcheck # we don't use SQL
    - zerologlint # not don't use Zerolog
    - wastedassign # `ineffassign` linter is enabled by default
    - spancheck # we don't use OpenTelemetry
    - loggercheck # we don't use Zap
    - unconvert # not enough profit from always enabling
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-checks:
        - ruleguard
      disabled-checks:
        - unnecessaryDefer
        - appendAssign
        - regexpMust
        - rangeValCopy
        - exitAfterDefer
        - elseif
        - dupBranchBody
        - assignOp
        - singleCaseSwitch
        - unlambda
        - captLocal
        - commentFormatting
        - ifElseChain
        - sloppyReassign
        - sprintfQuotedString
        - deferInLoop
        - nilValReturn
        - evalOrder
        - returnAfterHttpError
        - weakCond
        - builtinShadowDecl
        - uncheckedInlineErr
        - preferStringWriter
        - commentedOutCode
        - preferFprint
        - deprecatedComment
      enabled-tags:
        - performance
        - diagnostic
      settings:
        hugeParam:
          sizeThreshold: 1000
        rangeExprCopy:
          sizeThreshold: 512
          skipTestFuncs: true
        ruleguard:
          rules: rules.go
        underef:
          skipRecvDeref: true
    govet:
      enable:
        - nilness
        - unusedwrite
      disable:
        - deepequalerrors
        - fieldalignment
        - shadow
        - unsafeptr
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        text: not checked
      - linters:
          - staticcheck
        text: ST1019|ST1029|ST5011|QF1003|SA1019|QF1008|S1021|QF1001|SA6005|S1002|QF1002|QF1012|QF1006|ST1005|SA5011|ST1023|ST1012|QF1011|S1019|S1000|S1000|S1009|ST1008|S1016|S1016|ST1017|SA4009|QF1007|SA6002|QF1010|SA9003
      - linters:
          - gosec
          - perfsprint
          - unused
          - prealloc
        path: test\.go
      - linters:
          - gocritic
          - gosec
          - unused
        path: hack\.go
      - linters:
          - gocritic
          - gosec
          - unused
        path: cmd/devp2p
      - linters:
          - gocritic
          - gosec
        path: metrics/sample\.go
      - linters:
          - gocritic
          - gosec
        path: p2p/dnsdisc
    paths:
      - build/
      - vendor/
      - third_party$
      - builtin$
      - examples$
      - testdata
      - execution-spec-tests
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
    paths:
      - build/
      - vendor/
      - third_party$
      - builtin$
      - examples$
      - testdata
      - execution-spec-tests
