version: "2"
run:
  build-tags:
    - nosqlite
    - noboltdb
    - nosilkworm
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - durationcheck
    - fatcontext
    - gochecksumtype
    - gocritic
    - gosmopolitan
    - loggercheck
    - nilnesserr
    - perfsprint
    - prealloc
    - reassign
    - spancheck
    - unconvert
    - wastedassign
    - govet
  disable:
    - testifylint
    - staticcheck #TODO: enable me
    - errchkjson #TODO: enable me
    - makezero #TODO: enable me
    - noctx #TODO: enable me
    - errorlint #TODO: enable me
    - unused #TODO: enable me
    - contextcheck
    - err113
    - exhaustive
    - gocheckcompilerdirectives
    - gosec
    - musttag
    - nilerr
    - protogetter
    - recvcheck
    - unparam
    - wrapcheck
    - sqlclosecheck
    - zerologlint
    - rowserrcheck
  settings:
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      enabled-checks:
        - ruleguard
      disabled-checks:
        - unnecessaryDefer
        - appendAssign
        - regexpMust
        - rangeValCopy
        - exitAfterDefer
        - elseif
        - dupBranchBody
        - assignOp
        - singleCaseSwitch
        - unlambda
        - captLocal
        - commentFormatting
        - ifElseChain
        - sloppyReassign
        - sprintfQuotedString
        - deferInLoop
        - nilValReturn
        - evalOrder
        - returnAfterHttpError
        - weakCond
        - builtinShadowDecl
        - uncheckedInlineErr
        - preferStringWriter
        - commentedOutCode
        - preferFprint
      enabled-tags:
        - performance
        - diagnostic
      settings:
        hugeParam:
          sizeThreshold: 1000
        rangeExprCopy:
          sizeThreshold: 512
          skipTestFuncs: true
        ruleguard:
          rules: rules.go
        underef:
          skipRecvDeref: true
    govet:
      enable:
        - nilness
      disable:
        - deepequalerrors
        - fieldalignment
        - shadow
        - unsafeptr
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - golint
        text: should be
      - linters:
          - errcheck
        text: not checked
      - linters:
          - staticcheck
        text: SA(1019|1029|5011)
      - linters:
          - gocritic
          - gosec
          - perfsprint
          - unused
        path: test\.go
      - linters:
          - gocritic
          - gosec
          - unused
        path: hack\.go
      - linters:
          - gocritic
          - gosec
          - unused
        path: cmd/devp2p
      - linters:
          - gocritic
          - gosec
        path: metrics/sample\.go
      - linters:
          - gocritic
          - gosec
        path: p2p/dnsdisc
    paths:
      - third_party$
      - builtin$
      - examples$
      - testdata$
      - execution-spec-tests$
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: false
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - testdata$
      - execution-spec-tests$
