run:
  deadline: 10m


linters:
  enable:
    - unconvert
#    - gosec

linters-settings:
  govet:
    disable:
      - deepequalerrors
#      - fieldalignment
      - unsafeptr
  goconst:
    min-len: 2
    min-occurrences: 2
  gofmt:
    auto-fix: false

issues:
  exclude-rules:
    - linters:
        - golint
      text: "should be"
    - linters:
        - errcheck
      text: "not checked"
    - linters:
        - staticcheck
      text: "SA(1019|1029|5011)"
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gosec
        - unused
        - deadcode
