run:
  deadline: 10m

linters:
  disable-all: true
  enable:
    - gofmt
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - unused
    - varcheck
    - gocritic

linters-settings:
  gocritic:
    # Which checks should be enabled; can't be combined with 'disabled-checks';
    # See https://go-critic.github.io/overview#checks-overview
    # To check which checks are enabled run `GL_DEBUG=gocritic golangci-lint run`
    # By default list of stable checks is used.
    enabled-checks:
      - ruleguard
    #      - rangeValCopy
    #      - defaultCaseOrder

    # Which checks should be disabled; can't be combined with 'enabled-checks'; default is empty
    disabled-checks:
      - regexpMust
      - hugeParam
      - exitAfterDefer
      - elseif
      - dupBranchBody
      - assignOp
      - rangeValCopy
      - singleCaseSwitch
      - unlambda
      - captLocal
      - commentFormatting
      - ifElseChain
      - appendAssign

    # Enable multiple checks by tags, run `GL_DEBUG=gocritic golangci-lint run` to see all tags and checks.
    # Empty list by default. See https://github.com/go-critic/go-critic#usage -> section "Tags".
    enabled-tags:
      - performance
    disabled-tags:
      - experimental
    ruleguard:
      rules: "rules.go"
  govet:
    disable:
      - deepequalerrors
      - fieldalignment
      - shadow
      - unsafeptr
  goconst:
    min-len: 2
    min-occurrences: 2
  gofmt:
    auto-fix: false

issues:
  exclude-rules:
    - linters:
        - golint
      text: "should be"
    - linters:
        - errcheck
      text: "not checked"
    - linters:
        - staticcheck
      text: "SA(1019|1029|5011)"
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - gosec
        - unused
        - deadcode
        - gocritic
    - path: metrics/sample\.go
      linters:
        - gosec
        - gocritic
