project_name: erigon

release:
  disable: false
  draft: true
  prerelease: auto

builds:
  - id: darwin-amd64
    main: ./cmd/erigon
    binary: erigon
    goos: [ darwin ]
    goarch: [ amd64 ]
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - CC=o64-clang
      - CXX=o64-clang++
    tags: [ nosqlite, noboltdb ]
    ldflags:
      -s -w

  - id: darwin-arm64
    main: ./cmd/erigon
    binary: erigon
    goos: [ darwin ]
    goarch: [ arm64 ]
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/arm64
      - PKG_CONFIG_PATH=/sysroot/macos/arm64/usr/local/lib/pkgconfig
      - CC=oa64-clang
      - CXX=oa64-clang++
    tags: [ nosqlite, noboltdb ]
    ldflags:
      -s -w

  - id: linux-amd64
    main: ./cmd/erigon
    binary: erigon
    goos: [ linux ]
    goarch: [ amd64 ]
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/amd64
      - PKG_CONFIG_PATH=/sysroot/linux/amd64/usr/local/lib/pkgconfig
      - CC=gcc
      - CXX=g++
    tags: [ nosqlite, noboltdb ]
    ldflags:
      # We need to build a static binary because we are building in a glibc based system and running in a musl container
      -s -w -extldflags "-static"

  - id: linux-arm64
    main: ./cmd/erigon
    binary: erigon
    goos: [ linux ]
    goarch: [ arm64 ]
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/aarch64
      - PKG_CONFIG_PATH=/sysroot/linux/aarch64/usr/local/lib/pkgconfig
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    tags: [ nosqlite, noboltdb ]
    ldflags:
      # We need to build a static binary because we are building in a glibc based system and running in a musl container
      -s -w -extldflags "-static"

  - id: windows-amd64
    main: ./cmd/erigon
    binary: erigon
    goos: [ windows ]
    goarch: [ amd64 ]
    tags: [ nosqlite, noboltdb ]
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    ldflags:
      -s -w

  - id: windows-arm64
    main: ./cmd/erigon
    binary: erigon
    goos: [ windows ]
    goarch: [ arm64 ]
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/arm64
      - PKG_CONFIG_PATH=/sysroot/macos/arm64/usr/local/lib/pkgconfig
      - CC=oa64-clang
      - CXX=oa64-clang++
    ldflags:
      -s -w

snapshot:
  name_template: "{{ .Tag }}.next"

dockers:
  - image_templates:
      - thorax/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/ledgerwatch/{{ .ProjectName }}:{{ .Version }}-amd64
    dockerfile: Dockerfile.release
    use: buildx
    skip_push: true
    goarch: amd64
    ids:
      - linux-amd64
    build_flag_templates:
      - --platform=linux/amd64

  - image_templates:
      - thorax/{{ .ProjectName }}:{{ .Version }}-arm64
      - ghcr.io/ledgerwatch/{{ .ProjectName }}:{{ .Version }}-arm64
    dockerfile: Dockerfile.release
    skip_push: true
    use: buildx
    goarch: arm64
    ids:
      - linux-arm64
    build_flag_templates:
      - --platform=linux/arm64/v8

docker_manifests:
  - name_template: thorax/{{ .ProjectName }}:{{ .Version }}
    skip_push: true
    image_templates:
      - thorax/{{ .ProjectName }}:{{ .Version }}-amd64
      - thorax/{{ .ProjectName }}:{{ .Version }}-arm64

  - name_template: ghcr.io/ledgerwatch/{{ .ProjectName }}:{{ .Version }}
    skip_push: true
    image_templates:
      - ghcr.io/ledgerwatch/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/ledgerwatch/{{ .ProjectName }}:{{ .Version }}-arm64

  - name_template: thorax/{{ .ProjectName }}:latest
    skip_push: true
    image_templates:
      - thorax/{{ .ProjectName }}:{{ .Version }}-amd64
      - thorax/{{ .ProjectName }}:{{ .Version }}-arm64

  - name_template: ghcr.io/ledgerwatch/{{ .ProjectName }}:latest
    skip_push: true
    image_templates:
      - ghcr.io/ledgerwatch/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/ledgerwatch/{{ .ProjectName }}:{{ .Version }}-arm64

announce:
  slack:
    enabled: false
    # The name of the channel that the user selected as a destination for webhook messages.
    channel: '#code-releases'
