project_name: erigon

release:
  disable: false
  draft: true
  prerelease: auto

builds:
  - id: darwin-amd64-erigon
    main: ./cmd/erigon
    binary: erigon
    goos: [ darwin ]
    goarch: [ amd64 ]
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    tags: [ nosqlite, noboltdb ]
    ldflags: -s -w

  - id: darwin-amd64-abigen
    main: ./cmd/abigen
    binary: abigen
    goos: [ darwin ]
    goarch: [ amd64 ]
    env:
      - CC=o64-clang
      - CXX=o64-clang++
    tags: [ nosqlite, noboltdb ]
    ldflags: -s -w

  - id: darwin-amd64-caplin-phase1
    main: ./cmd/caplin-phase1
    binary: caplin-phase1
    goos: [ darwin ]
    goarch: [ arm64 ]
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    tags: [ nosqlite, noboltdb ]
    ldflags: -s -w

  - id: darwin-amd64-caplin-regression
    main: ./cmd/caplin-regression
    binary: caplin-regression
    goos: [ darwin ]
    goarch: [ arm64 ]
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    tags: [ nosqlite, noboltdb ]
    ldflags: -s -w

  - id: darwin-amd64-devnet
    main: ./cmd/devnet
    binary: devnet
    goos: [ darwin ]
    goarch: [ arm64 ]
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    tags: [ nosqlite, noboltdb ]
    ldflags: -s -w

  - id: darwin-amd64-downloader
    main: ./cmd/downloader
    binary: downloader
    goos: [ darwin ]
    goarch: [ arm64 ]
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    tags: [ nosqlite, noboltdb ]
    ldflags: -s -w

  - id: darwin-amd64-evm
    main: ./cmd/evm
    binary: evm
    goos: [ darwin ]
    goarch: [ arm64 ]
    env:
      - CC=oa64-clang
      - CXX=oa64-clang++
    tags: [ nosqlite, noboltdb ]
    ldflags: -s -w

  - id: darwin-amd64-hack
      main: ./cmd/hack
      binary: hack
      goos: [ darwin ]
      goarch: [ arm64 ]
      env:
        - CC=oa64-clang
        - CXX=oa64-clang++
      tags: [ nosqlite, noboltdb ]
      ldflags: -s -w

  - id: darwin-amd64-integration
      main: ./cmd/integration
      binary: integration
      goos: [ darwin ]
      goarch: [ arm64 ]
      env:
        - CC=oa64-clang
        - CXX=oa64-clang++
      tags: [ nosqlite, noboltdb ]
      ldflags: -s -w

  - id: darwin-amd64-observer
      main: ./cmd/integration
      binary: integration
      goos: [ darwin ]
      goarch: [ arm64 ]
      env:
        - CC=oa64-clang
        - CXX=oa64-clang++
      tags: [ nosqlite, noboltdb ]
      ldflags: -s -w

  - id: darwin-amd64-pics
      main: ./cmd/pics
      binary: pics
      goos: [ darwin ]
      goarch: [ arm64 ]
      env:
        - CC=oa64-clang
        - CXX=oa64-clang++
      tags: [ nosqlite, noboltdb ]
      ldflags: -s -w

  - id: darwin-amd64-rpcdaemon
      main: ./cmd/rpcdaemon
      binary: rpcdaemon
      goos: [ darwin ]
      goarch: [ arm64 ]
      env:
        - CC=oa64-clang
        - CXX=oa64-clang++
      tags: [ nosqlite, noboltdb ]
      ldflags: -s -w

  - id: darwin-amd64-rpctest
      main: ./cmd/rpctest
      binary: rpctest
      goos: [ darwin ]
      goarch: [ arm64 ]
      env:
        - CC=oa64-clang
        - CXX=oa64-clang++
      tags: [ nosqlite, noboltdb ]
      ldflags: -s -w

  - id: darwin-amd64-sentinel
      main: ./cmd/sentinel
      binary: sentinel
      goos: [ darwin ]
      goarch: [ arm64 ]
      env:
        - CC=oa64-clang
        - CXX=oa64-clang++
      tags: [ nosqlite, noboltdb ]
      ldflags: -s -w

  - id: darwin-amd64-sentry
      main: ./cmd/sentry
      binary: sentry
      goos: [ darwin ]
      goarch: [ arm64 ]
      env:
        - CC=oa64-clang
        - CXX=oa64-clang++
      tags: [ nosqlite, noboltdb ]
      ldflags: -s -w

  - id: darwin-amd64-state
      main: ./cmd/state
      binary: state
      goos: [ darwin ]
      goarch: [ arm64 ]
      env:
        - CC=oa64-clang
        - CXX=oa64-clang++
      tags: [ nosqlite, noboltdb ]
      ldflags: -s -w

  - id: darwin-amd64-txpool
      main: ./cmd/txpool
      binary: txpool
      goos: [ darwin ]
      goarch: [ arm64 ]
      env:
        - CC=oa64-clang
        - CXX=oa64-clang++
      tags: [ nosqlite, noboltdb ]
      ldflags: -s -w

  - id: darwin-amd64-verkle
      main: ./cmd/verkle
      binary: verkle
      goos: [ darwin ]
      goarch: [ arm64 ]
      env:
        - CC=oa64-clang
        - CXX=oa64-clang++
      tags: [ nosqlite, noboltdb ]
      ldflags: -s -w

  - id: linux-amd64
    main: ./cmd/erigon
    binary: erigon
    goos: [ linux ]
    goarch: [ amd64 ]
    env:
      - CC=x86_64-linux-gnu-gcc
      - CXX=x86_64-linux-gnu-g++
    tags: [ nosqlite, noboltdb ]
    ldflags: -s -w -extldflags "-static" # We need to build a static binary because we are building in a glibc based system and running in a musl container

  - id: linux-arm64
    main: ./cmd/erigon
    binary: erigon
    goos: [ linux ]
    goarch: [ arm64 ]
    env:
      - CC=aarch64-linux-gnu-gcc
      - CXX=aarch64-linux-gnu-g++
    tags: [ nosqlite, noboltdb ]
    ldflags: -s -w -extldflags "-static" # We need to build a static binary because we are building in a glibc based system and running in a musl container

  - id: windows-amd64
    main: ./cmd/erigon
    binary: erigon
    goos: [ windows ]
    goarch: [ amd64 ]
    env:
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    tags: [ nosqlite, noboltdb ]
    ldflags: -s -w


snapshot:
  name_template: "{{ .Tag }}.next"

dockers:
  - image_templates:
      - thorax/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/ledgerwatch/{{ .ProjectName }}:{{ .Version }}-amd64
    dockerfile: Dockerfile
    use: buildx
    skip_push: true
    goarch: amd64
    ids:
      - linux-amd64
    build_flag_templates:
      - --platform=linux/amd64

  - image_templates:
      - thorax/{{ .ProjectName }}:{{ .Version }}-arm64
      - ghcr.io/ledgerwatch/{{ .ProjectName }}:{{ .Version }}-arm64
    dockerfile: Dockerfile
    skip_push: true
    use: buildx
    goarch: arm64
    ids:
      - linux-arm64
    build_flag_templates:
      - --platform=linux/arm64/v8

docker_manifests:
  - name_template: thorax/{{ .ProjectName }}:{{ .Version }}
    skip_push: true
    image_templates:
      - thorax/{{ .ProjectName }}:{{ .Version }}-amd64
      - thorax/{{ .ProjectName }}:{{ .Version }}-arm64

  - name_template: ghcr.io/ledgerwatch/{{ .ProjectName }}:{{ .Version }}
    skip_push: true
    image_templates:
      - ghcr.io/ledgerwatch/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/ledgerwatch/{{ .ProjectName }}:{{ .Version }}-arm64

  - name_template: thorax/{{ .ProjectName }}:latest
    skip_push: true
    image_templates:
      - thorax/{{ .ProjectName }}:{{ .Version }}-amd64
      - thorax/{{ .ProjectName }}:{{ .Version }}-arm64

  - name_template: ghcr.io/ledgerwatch/{{ .ProjectName }}:latest
    skip_push: true
    image_templates:
      - ghcr.io/ledgerwatch/{{ .ProjectName }}:{{ .Version }}-amd64
      - ghcr.io/ledgerwatch/{{ .ProjectName }}:{{ .Version }}-arm64

announce:
  slack:
    enabled: false
    # The name of the channel that the user selected as a destination for webhook messages.
    channel: '#code-releases'