run:
  timeout: 10m
  build-tags:
    - nosqlite
    - noboltdb

linters:
  presets:
    - bugs
    - error
    - unused
    - performance
  disable:
    - gosec
    - exhaustive
    - musttag
    - contextcheck
    - wrapcheck
    - err113
    - unparam
    - makezero
    - testifylint #TODO: enable me
    - perfsprint #TODO: enable me
    - protogetter
    - typecheck
  enable:
    - unconvert
    - predeclared
    - wastedassign
    - thelper
    - gofmt
    - gocritic
#    - revive
#    - forcetypeassert
#    - stylecheck

linters-settings:
  gocritic: # see https://golangci-lint.run/usage/linters/#gocritic and https://go-critic.github.io/overview#checks-overview
    enabled-tags:
      - performance
      - diagnostic
    enabled-checks:
      - ruleguard
    disabled-checks:
      - rangeValCopy
      - exitAfterDefer
      - elseif
      - dupBranchBody
      - assignOp
      - singleCaseSwitch
      - captLocal
      - commentFormatting
      - ifElseChain
      - appendAssign
      - preferFprint

      # diagnostigs tag: possible bugs. need enable checks in future
      - sloppyReassign
      - sprintfQuotedString
      - deferInLoop
      - nilValReturn
      - evalOrder
      - commentedOutCode
      - returnAfterHttpError
      - weakCond
      - builtinShadowDecl
      - unnecessaryDefer
      - uncheckedInlineErr
      - preferStringWriter

    settings:
      ruleguard:
        rules: "rules.go"
      hugeParam:
        # size in bytes that makes the warning trigger (default 80)
        sizeThreshold: 1000
      rangeExprCopy:
        # size in bytes that makes the warning trigger (default 512)
        sizeThreshold: 512
        # whether to check test functions (default true)
        skipTestFuncs: true
      underef:
        # whether to skip (*x).method() calls where x is a pointer receiver (default true)
        skipRecvDeref: true

  govet:
    disable:
      - deepequalerrors
      - shadow
      - unsafeptr
  goconst:
    min-len: 2
    min-occurrences: 2
  gofmt:
    simplify: false

issues:
  exclude-rules:
    - linters:
        - golint
      text: "should be"
    - linters:
        - errcheck
      text: "not checked"
    - linters:
        - staticcheck
      text: "SA(1019|1029|5011)"
    # Exclude some linters from running on tests files.
    - path: test\.go
      linters:
        - gosec
        - unused
        - gocritic
        - perfsprint
    - path: hack\.go
      linters:
        - gosec
        - unused
        - gocritic
    - path: cmd/devp2p
      linters:
        - gosec
        - unused
        - gocritic
    - path: metrics/sample\.go
      linters:
        - gosec
        - gocritic
    - path: p2p/simulations
      linters:
        - gosec
        - gocritic
