name: Cleanup Erigon
description: Save module cache and warn about uncached tests

inputs:
  tag:
    description: "Optional tag appended to the gomodcache prefix (e.g. 'lint' produces 'gomodcache|lint')"
    required: false
    default: ""
  modcache-restored-key:
    description: "Override for the restored modcache key. Falls back to ERIGON_CI_MODCACHE_RESTORED_KEY env var."
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: ./.github/actions/save-mod-cache
      if: ${{ always() }}
      with:
        modcache: ${{ env.ERIGON_CI_MODCACHE }}
        prefix: ${{ inputs.tag != '' && format('gomodcache|{0}', inputs.tag) || 'gomodcache' }}
        restored-key: ${{ inputs.modcache-restored-key || env.ERIGON_CI_MODCACHE_RESTORED_KEY }}

    - name: Check for uncached tests
      if: hashFiles('run.log') != ''
      shell: bash
      run: |
        ran=$(grep -cE '^ok\s.*[0-9]+\.[0-9]+s$' run.log || true)
        if [ "$ran" -gt 0 ]; then
          echo "::warning::$ran test package(s) ran without caching"
        fi
