name: Cleanup Erigon
description: Save module cache (when not handled by setup-erigon) and warn about uncached tests

inputs:
  tag:
    description: "Optional tag for the modcache key (e.g. 'lint'). Defaults to ERIGON_CI_MODCACHE_MODE env var."
    required: false
    default: ""
  modcache-restored-key:
    description: "Override for the restored modcache key. Falls back to ERIGON_CI_MODCACHE_RESTORED_KEY env var."
    required: false
    default: ""

runs:
  using: composite
  steps:
    - uses: ./.github/actions/save-build-cache
      if: ${{ always() && env.ERIGON_CI_GOCACHE != '' }}
      with:
        gocache: ${{ env.ERIGON_CI_GOCACHE }}
        goversion: ${{ env.ERIGON_CI_GOVERSION }}
        workflow: ${{ env.ERIGON_CI_WORKFLOW }}
        extra-key: ${{ env.ERIGON_CI_BUILD_CACHE_EXTRA_KEY }}
        restored-key: ${{ env.ERIGON_CI_BUILD_CACHE_RESTORED_KEY }}

    - uses: ./.github/actions/save-mod-cache
      if: ${{ always() && env.ERIGON_CI_MODCACHE_MODE != 'download' }}
      with:
        modcache-path: ${{ env.ERIGON_CI_MODCACHE }}
        tag: ${{ inputs.tag || env.ERIGON_CI_MODCACHE_MODE }}
        restored-key: ${{ inputs.modcache-restored-key || env.ERIGON_CI_MODCACHE_RESTORED_KEY }}

    - name: Save submodule git objects cache
      if: >-
        ${{ always()
        && env.ERIGON_CI_SUBMODULE_CACHE_KEY != ''
        && env.ERIGON_CI_SUBMODULE_CACHE_RESTORED_KEY != env.ERIGON_CI_SUBMODULE_CACHE_KEY }}
      uses: actions/cache/save@v4
      with:
        path: .git/modules
        key: ${{ env.ERIGON_CI_SUBMODULE_CACHE_KEY }}

    - name: Check for uncached tests
      if: hashFiles('run.log') != ''
      shell: bash
      run: |
        ran=$(grep -cE '^ok\s.*[0-9]+\.[0-9]+s$' run.log || true)
        if [ "$ran" -gt 0 ]; then
          echo "::warning::$ran test package(s) ran without caching"
        fi
