name: Cleanup Erigon
description: Warn if any tests ran without caching

runs:
  using: composite
  steps:
    - name: Check for uncached tests
      if: hashFiles('run.log') != ''
      shell: bash
      run: |
        ran=$(grep -cE '^ok\s.*[0-9]+\.[0-9]+s$' run.log || true)
        if [ "$ran" -gt 0 ]; then
          echo "::warning::$ran test package(s) ran without caching"
        fi
