{
 "title": "ErigonQA",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Tip Tracking - Ethereum", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Sync time & dir size (main)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"mainnet\",\"branch\":\"main\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"total-sync-time_%\":\"$results.measures.total-sync-time_%\",\"dir-size-increment_%\":\"$results.measures.dir-size-increment_%\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"mainnet\",\n            branch: \"main\",\n            outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'total-sync-time_%': '$results.measures.total-sync-time_%',\n            'dir-size-increment_%': '$results.measures.dir-size-increment_%'\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"mainnet\",\"branch\":\"main\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"mainnet\",\n            branch: \"main\",\n            outcome: \"failure\",\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'failure': { $literal: 0 },\n        }\n    }\n])\n"
    }
   ]
  },
  {
   "title": "Sync time & dir size (release/2.60-2.61)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"mainnet\",\"branch\":\"release/2.60\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"total-sync-time_%(2.60)\":\"$results.measures.total-sync-time_%\",\"dir-size-increment_%(2.60)\":\"$results.measures.dir-size-increment_%\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"mainnet\",\n            branch: \"release/2.60\",\n            outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'total-sync-time_%(2.60)': '$results.measures.total-sync-time_%',\n            'dir-size-increment_%(2.60)': '$results.measures.dir-size-increment_%'\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"mainnet\",\"branch\":\"release/2.60\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"mainnet\",\n            branch: \"release/2.60\",\n            outcome: \"failure\",\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            failure: { $literal: 0 },\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"mainnet\",\"branch\":\"release/2.61\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"total-sync-time_%\":\"$results.measures.total-sync-time_%\",\"dir-size-increment_%\":\"$results.measures.dir-size-increment_%\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"mainnet\",\n            branch: \"release/2.61\",\n            outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'total-sync-time_%': '$results.measures.total-sync-time_%',\n            'dir-size-increment_%': '$results.measures.dir-size-increment_%'\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"mainnet\",\"branch\":\"release/2.61\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"mainnet\",\n            branch: \"release/2.61\",\n            outcome: \"failure\",\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            failure: { $literal: 0 },\n        }\n    }\n])\n"
    }
   ]
  },
  {
   "title": "Per block size (main)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"mainnet\",\"branch\":\"main\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"per-block-size-increment_mb\":\"$results.measures.per-block-size-increment_mb\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"mainnet\",\n            branch: \"main\",\n            outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'per-block-size-increment_mb': '$results.measures.per-block-size-increment_mb'\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"mainnet\",\"branch\":\"main\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"mainnet\",\n            branch: \"main\",\n            outcome: \"failure\"\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            failure: { $literal: 0 },\n        }\n    }\n])\n"
    }
   ]
  },
  {
   "title": "Per block size (release/2.60-2.61)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"mainnet\",\"branch\":\"release/2.60\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"per-block-size-increment_mb(2.60)\":\"$results.measures.per-block-size-increment_mb\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"mainnet\",\n            branch: \"release/2.60\",\n            outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'per-block-size-increment_mb(2.60)': '$results.measures.per-block-size-increment_mb'\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"mainnet\",\"branch\":\"release/2.60\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"mainnet\",\n            branch: \"release/2.60\",\n            outcome: \"failure\"\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            failure: { $literal: 0 },\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"mainnet\",\"branch\":\"release/2.61\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"per-block-size-increment_mb\":\"$results.measures.per-block-size-increment_mb\"}}])",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"mainnet\",\n            branch: \"release/2.61\",\n            outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'per-block-size-increment_mb': '$results.measures.per-block-size-increment_mb'\n        }\n    }\n])"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"mainnet\",\"branch\":\"release/2.61\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"mainnet\",\n            branch: \"release/2.61\",\n            outcome: \"failure\"\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            failure: { $literal: 0 },\n        }\n    }\n])\n"
    }
   ]
  },
  { "title": "Tip Tracking - Gnosis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Sync time & dir size (main)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"gnosis\",\"branch\":\"main\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"total-sync-time_%\":\"$results.measures.total-sync-time_%\",\"dir-size-increment_%\":\"$results.measures.dir-size-increment_%\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"gnosis\",\n            branch: \"main\",\n            outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'total-sync-time_%': '$results.measures.total-sync-time_%',\n            'dir-size-increment_%': '$results.measures.dir-size-increment_%'\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"gnosis\",\"branch\":\"main\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"gnosis\",\n            branch: \"main\",\n            outcome: \"failure\",\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            failure: { $literal: 0 },\n        }\n    }\n])\n"
    }
   ]
  },
  {
   "title": "Sync time & dir size (release/2.60-2.61)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"gnosis\",\"branch\":\"release/2.60\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"total-sync-time_%(2.60)\":\"$results.measures.total-sync-time_%\",\"dir-size-increment_%(2.60)\":\"$results.measures.dir-size-increment_%\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"gnosis\",\n            branch: \"release/2.60\",\n            outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'total-sync-time_%(2.60)': '$results.measures.total-sync-time_%',\n            'dir-size-increment_%(2.60)': '$results.measures.dir-size-increment_%'\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"gnosis\",\"branch\":\"release/2.60\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"gnosis\",\n            branch: \"release/2.60\",\n            outcome: \"failure\",\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            failure: { $literal: 0 },\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"gnosis\",\"branch\":\"release/2.61\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"total-sync-time_%\":\"$results.measures.total-sync-time_%\",\"dir-size-increment_%\":\"$results.measures.dir-size-increment_%\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"gnosis\",\n            branch: \"release/2.61\",\n            outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'total-sync-time_%': '$results.measures.total-sync-time_%',\n            'dir-size-increment_%': '$results.measures.dir-size-increment_%'\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"gnosis\",\"branch\":\"release/2.61\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"gnosis\",\n            branch: \"release/2.61\",\n            outcome: \"failure\",\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            failure: { $literal: 0 },\n        }\n    }\n])\n"
    }
   ]
  },
  {
   "title": "Per block size (main)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"gnosis\",\"branch\":\"main\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"per-block-size-increment_mb\":\"$results.measures.per-block-size-increment_mb\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"gnosis\",\n            branch: \"main\",\n            outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'per-block-size-increment_mb': '$results.measures.per-block-size-increment_mb'\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"gnosis\",\"branch\":\"main\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"gnosis\",\n            branch: \"main\",\n            outcome: \"failure\",\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            failure: { $literal: 0 },\n        }\n    }\n])\n"
    }
   ]
  },
  {
   "title": "Per block size (release/2.60-2.61)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"gnosis\",\"branch\":\"release/2.60\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"per-block-size-increment_mb(2.60)\":\"$results.measures.per-block-size-increment_mb\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"gnosis\",\n            branch: \"release/2.60\",\n            outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'per-block-size-increment_mb(2.60)': '$results.measures.per-block-size-increment_mb'\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"gnosis\",\"branch\":\"release/2.60\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"gnosis\",\n            branch: \"release/2.60\",\n            outcome: \"failure\",\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            failure: { $literal: 0 },\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"gnosis\",\"branch\":\"release/2.61\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"per-block-size-increment_mb\":\"$results.measures.per-block-size-increment_mb\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"gnosis\",\n            branch: \"release/2.61\",\n            outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'per-block-size-increment_mb': '$results.measures.per-block-size-increment_mb'\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"gnosis\",\"branch\":\"release/2.61\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"gnosis\",\n            branch: \"release/2.61\",\n            outcome: \"failure\",\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            failure: { $literal: 0 },\n        }\n    }\n])\n"
    }
   ]
  },
  { "title": "Tip Tracking - Polygon", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Sync time & dir size (main)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"bor-mainnet\",\"branch\":\"main\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"total-sync-time_%\":\"$results.measures.total-sync-time_%\",\"dir-size-increment_%\":\"$results.measures.dir-size-increment_%\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"bor-mainnet\",\n            branch: \"main\",\n            outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'total-sync-time_%': '$results.measures.total-sync-time_%',\n            'dir-size-increment_%': '$results.measures.dir-size-increment_%'\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"tip-tracking\",\"repo\":\"erigon\",\"chain\":\"bor-mainnet\",\"branch\":\"main\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"tip-tracking\",\n            repo: \"erigon\",\n            chain: \"bor-mainnet\",\n            branch: \"main\",\n            outcome: \"failure\",\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'failure': { $literal: 0 },\n        }\n    }\n])\n"
    }
   ]
  },
  {
   "title": "Sync from scratch - mainnet (minimal node)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }
  },
  {
   "title": "Sync time & dir size (main branch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch-minimal-node\",\"repo\":\"erigon\",\"chain\":\"mainnet\",\"branch\":\"main\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"total-sync-time_%\":\"$results.measures.total-sync-time_%\",\"dir-size-increment_%\":\"$results.measures.dir-size-increment_%\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"sync-from-scratch-minimal-node\",\n            repo: \"erigon\",\n            chain: \"mainnet\",\n            branch: \"main\",\n            outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'total-sync-time_%': '$results.measures.total-sync-time_%',\n            'dir-size-increment_%': '$results.measures.dir-size-increment_%'\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch-minimal-node\",\"repo\":\"erigon\",\"chain\":\"mainnet\",\"branch\":\"main\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"sync-from-scratch-minimal-node\",\n            repo: \"erigon\",\n            chain: \"mainnet\",\n            branch: \"main\",\n            outcome: \"failure\",\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            failure: { $literal: 0 },\n        }\n    }\n])\n"
    }
   ]
  },
  {
   "title": "Time to the tip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch-minimal-node\",\"repo\":\"erigon\",\"chain\":\"mainnet\",\"branch\":\"main\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"time_difference_hours\":{\"$ifNull\":[{\"$round\":[{\"$divide\":[{\"$subtract\":[{\"$dateFromString\":{\"dateString\":\"$results.measures.sync-start-time\",\"format\":\"%Y-%m-%d %H:%M:%S\"}},{\"$dateFromString\":{\"dateString\":\"$results.measures.start-time\",\"format\":\"%Y-%m-%d %H:%M:%S\"}}]},3600000]},2]},0]}}}])",
     "query": "db.getCollection(\"TestResults\").aggregate([\n  {\n    $match: {\n      test: \"sync-from-scratch-minimal-node\",\n      repo: \"erigon\",\n      chain: \"mainnet\",\n      branch: \"main\",\n      outcome: { $ne: \"failure\" },\n    }\n  },\n  {\n    $project: {\n      date: 1,\n      'time_difference_hours': {\n        $ifNull: [\n          {\n            $round: [\n              {\n                $divide: [\n                  { $subtract: [\n                    { $dateFromString: { dateString: \"$results.measures.sync-start-time\", format: \"%Y-%m-%d %H:%M:%S\" } },\n                    { $dateFromString: { dateString: \"$results.measures.start-time\", format: \"%Y-%m-%d %H:%M:%S\" } }\n                  ] },\n                  3600000 \n                ]\n              },\n              2 \n            ]\n          },\n          0 \n        ]\n      }\n    }\n  }\n])"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch-minimal-node\",\"repo\":\"erigon\",\"chain\":\"mainnet\",\"branch\":\"main\"}},{\"$project\":{\"date\":1,\"failure\":{\"$ifNull\":[{\"$round\":[{\"$divide\":[{\"$subtract\":[{\"$dateFromString\":{\"dateString\":\"$results.measures.sync-start-time\",\"format\":\"%Y-%m-%d %H:%M:%S\"}},{\"$dateFromString\":{\"dateString\":\"$results.measures.start-time\",\"format\":\"%Y-%m-%d %H:%M:%S\"}}]},3600000]},2]},0]}}},{\"$match\":{\"failure\":0}}])",
     "query": "db.getCollection(\"TestResults\").aggregate([\n  {\n    $match: {\n      test: \"sync-from-scratch-minimal-node\",\n      repo: \"erigon\",\n      chain: \"mainnet\",\n      branch: \"main\"\n    }\n  },\n  {\n    $project: {\n      date: 1,\n      'failure': {\n        $ifNull: [\n          {\n            $round: [\n              {\n                $divide: [\n                  { $subtract: [\n                    { $dateFromString: { dateString: \"$results.measures.sync-start-time\", format: \"%Y-%m-%d %H:%M:%S\" } },\n                    { $dateFromString: { dateString: \"$results.measures.start-time\", format: \"%Y-%m-%d %H:%M:%S\" } }\n                  ] },\n                  3600000\n                ]\n              },\n              2\n            ]\n          },\n          0\n        ]\n      }\n    }\n  },\n  {\n    $match: {\n      'failure': 0\n    }\n  }\n])"
    }
   ]
  },
  {
   "title": "Per block size (main branch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch-minimal-node\",\"repo\":\"erigon\",\"chain\":\"mainnet\",\"branch\":\"main\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"per-block-size-increment_mb\":\"$results.measures.per-block-size-increment_mb\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"sync-from-scratch-minimal-node\",\n            repo: \"erigon\",\n            chain: \"mainnet\",\n            branch: \"main\",\n            outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'per-block-size-increment_mb': '$results.measures.per-block-size-increment_mb'\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch-minimal-node\",\"repo\":\"erigon\",\"chain\":\"mainnet\",\"branch\":\"main\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"sync-from-scratch-minimal-node\",\n            repo: \"erigon\",\n            chain: \"mainnet\",\n            branch: \"main\",\n            outcome: \"failure\",\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            failure: { $literal: 0 },\n        }\n    }\n])\n"
    }
   ]
  },
  { "title": "Sync from scratch - Holesky", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Sync time & dir size (main branch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch\",\"repo\":\"erigon\",\"chain\":\"holesky\",\"branch\":\"main\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"total-sync-time_%\":\"$results.measures.total-sync-time_%\",\"dir-size-increment_%\":\"$results.measures.dir-size-increment_%\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"sync-from-scratch\",\n            repo: \"erigon\",\n            chain: \"holesky\",\n            branch: \"main\",\n            outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'total-sync-time_%': '$results.measures.total-sync-time_%',\n            'dir-size-increment_%': '$results.measures.dir-size-increment_%'\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch\",\"repo\":\"erigon\",\"chain\":\"holesky\",\"branch\":\"main\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"sync-from-scratch\",\n            repo: \"erigon\",\n            chain: \"holesky\",\n            branch: \"main\",\n            outcome: \"failure\",\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            failure: { $literal: 0 },\n        }\n    }\n])\n"
    }
   ]
  },
  {
   "title": "Time to the tip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch\",\"repo\":\"erigon\",\"chain\":\"holesky\",\"branch\":\"main\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"time_difference_hours\":{\"$ifNull\":[{\"$round\":[{\"$divide\":[{\"$subtract\":[{\"$dateFromString\":{\"dateString\":\"$results.measures.sync-start-time\",\"format\":\"%Y-%m-%d %H:%M:%S\"}},{\"$dateFromString\":{\"dateString\":\"$results.measures.start-time\",\"format\":\"%Y-%m-%d %H:%M:%S\"}}]},3600000]},2]},0]}}}])",
     "query": "db.getCollection(\"TestResults\").aggregate([\n  {\n    $match: {\n      test: \"sync-from-scratch\",\n      repo: \"erigon\",\n      chain: \"holesky\",\n      branch: \"main\",\n      outcome: { $ne: \"failure\" },\n    }\n  },\n  {\n    $project: {\n      date: 1,\n      'time_difference_hours': {\n        $ifNull: [\n          {\n            $round: [\n              {\n                $divide: [\n                  { $subtract: [\n                    { $dateFromString: { dateString: \"$results.measures.sync-start-time\", format: \"%Y-%m-%d %H:%M:%S\" } },\n                    { $dateFromString: { dateString: \"$results.measures.start-time\", format: \"%Y-%m-%d %H:%M:%S\" } }\n                  ] },\n                  3600000 \n                ]\n              },\n              2 \n            ]\n          },\n          0 \n        ]\n      }\n    }\n  }\n])"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch\",\"repo\":\"erigon\",\"chain\":\"holesky\",\"branch\":\"main\"}},{\"$project\":{\"date\":1,\"failure\":{\"$ifNull\":[{\"$round\":[{\"$divide\":[{\"$subtract\":[{\"$dateFromString\":{\"dateString\":\"$results.measures.sync-start-time\",\"format\":\"%Y-%m-%d %H:%M:%S\"}},{\"$dateFromString\":{\"dateString\":\"$results.measures.start-time\",\"format\":\"%Y-%m-%d %H:%M:%S\"}}]},3600000]},2]},0]}}},{\"$match\":{\"failure\":0}}])",
     "query": "db.getCollection(\"TestResults\").aggregate([\n  {\n    $match: {\n      test: \"sync-from-scratch\",\n      repo: \"erigon\",\n      chain: \"holesky\",\n      branch: \"main\"\n    }\n  },\n  {\n    $project: {\n      date: 1,\n      'failure': {\n        $ifNull: [\n          {\n            $round: [\n              {\n                $divide: [\n                  { $subtract: [\n                    { $dateFromString: { dateString: \"$results.measures.sync-start-time\", format: \"%Y-%m-%d %H:%M:%S\" } },\n                    { $dateFromString: { dateString: \"$results.measures.start-time\", format: \"%Y-%m-%d %H:%M:%S\" } }\n                  ] },\n                  3600000\n                ]\n              },\n              2\n            ]\n          },\n          0\n        ]\n      }\n    }\n  },\n  {\n    $match: {\n      'failure': 0\n    }\n  }\n])"
    }
   ]
  },
  {
   "title": "Per block size (main branch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch\",\"repo\":\"erigon\",\"chain\":\"holesky\",\"branch\":\"main\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"per-block-size-increment_mb\":\"$results.measures.per-block-size-increment_mb\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"sync-from-scratch\",\n            repo: \"erigon\",\n            chain: \"holesky\",\n            branch: \"main\",\n            outcome: { $ne: \"failure\" } ,\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'per-block-size-increment_mb': '$results.measures.per-block-size-increment_mb'\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch\",\"repo\":\"erigon\",\"chain\":\"holesky\",\"branch\":\"main\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"sync-from-scratch\",\n            repo: \"erigon\",\n            chain: \"holesky\",\n            branch: \"main\",\n            outcome: \"failure\",\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            failure: { $literal: 0 },\n        }\n    }\n])\n"
    }
   ]
  },
  { "title": "Sync from scratch - Sepolia", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 } },
  {
   "title": "Sync time & dir size (main branch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch\",\"repo\":\"erigon\",\"chain\":\"sepolia\",\"branch\":\"main\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"total-sync-time_%\":\"$results.measures.total-sync-time_%\",\"dir-size-increment_%\":\"$results.measures.dir-size-increment_%\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"sync-from-scratch\",\n            repo: \"erigon\",\n            chain: \"sepolia\",\n            branch: \"main\",\n            outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'total-sync-time_%': '$results.measures.total-sync-time_%',\n            'dir-size-increment_%': '$results.measures.dir-size-increment_%'\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch\",\"repo\":\"erigon\",\"chain\":\"sepolia\",\"branch\":\"main\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"sync-from-scratch\",\n            repo: \"erigon\",\n            chain: \"sepolia\",\n            branch: \"main\",\n            outcome: \"failure\",\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            failure: { $literal: 0 },\n        }\n    }\n])\n"
    }
   ]
  },
  {
   "title": "Time to the tip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch\",\"repo\":\"erigon\",\"chain\":\"sepolia\",\"branch\":\"main\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"time_difference_hours\":{\"$ifNull\":[{\"$round\":[{\"$divide\":[{\"$subtract\":[{\"$dateFromString\":{\"dateString\":\"$results.measures.sync-start-time\",\"format\":\"%Y-%m-%d %H:%M:%S\"}},{\"$dateFromString\":{\"dateString\":\"$results.measures.start-time\",\"format\":\"%Y-%m-%d %H:%M:%S\"}}]},3600000]},2]},0]}}}])",
     "query": "db.getCollection(\"TestResults\").aggregate([\n  {\n    $match: {\n      test: \"sync-from-scratch\",\n      repo: \"erigon\",\n      chain: \"sepolia\",\n      branch: \"main\",\n      outcome: { $ne: \"failure\" },\n    }\n  },\n  {\n    $project: {\n      date: 1,\n      'time_difference_hours': {\n        $ifNull: [\n          {\n            $round: [\n              {\n                $divide: [\n                  { $subtract: [\n                    { $dateFromString: { dateString: \"$results.measures.sync-start-time\", format: \"%Y-%m-%d %H:%M:%S\" } },\n                    { $dateFromString: { dateString: \"$results.measures.start-time\", format: \"%Y-%m-%d %H:%M:%S\" } }\n                  ] },\n                  3600000 \n                ]\n              },\n              2 \n            ]\n          },\n          0 \n        ]\n      }\n    }\n  }\n])"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch\",\"repo\":\"erigon\",\"chain\":\"sepolia\",\"branch\":\"main\"}},{\"$project\":{\"date\":1,\"failure\":{\"$ifNull\":[{\"$round\":[{\"$divide\":[{\"$subtract\":[{\"$dateFromString\":{\"dateString\":\"$results.measures.sync-start-time\",\"format\":\"%Y-%m-%d %H:%M:%S\"}},{\"$dateFromString\":{\"dateString\":\"$results.measures.start-time\",\"format\":\"%Y-%m-%d %H:%M:%S\"}}]},3600000]},2]},0]}}},{\"$match\":{\"failure\":0}}])",
     "query": "db.getCollection(\"TestResults\").aggregate([\n  {\n    $match: {\n      test: \"sync-from-scratch\",\n      repo: \"erigon\",\n      chain: \"sepolia\",\n      branch: \"main\"\n    }\n  },\n  {\n    $project: {\n      date: 1,\n      'failure': {\n        $ifNull: [\n          {\n            $round: [\n              {\n                $divide: [\n                  { $subtract: [\n                    { $dateFromString: { dateString: \"$results.measures.sync-start-time\", format: \"%Y-%m-%d %H:%M:%S\" } },\n                    { $dateFromString: { dateString: \"$results.measures.start-time\", format: \"%Y-%m-%d %H:%M:%S\" } }\n                  ] },\n                  3600000\n                ]\n              },\n              2\n            ]\n          },\n          0\n        ]\n      }\n    }\n  },\n  {\n    $match: {\n      'failure': 0\n    }\n  }\n])"
    }
   ]
  },
  {
   "title": "Per block size (main branch)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch\",\"repo\":\"erigon\",\"chain\":\"sepolia\",\"branch\":\"main\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"per-block-size-increment_mb\":\"$results.measures.per-block-size-increment_mb\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"sync-from-scratch\",\n            repo: \"erigon\",\n            chain: \"sepolia\",\n            branch: \"main\",\n            outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'per-block-size-increment_mb': '$results.measures.per-block-size-increment_mb'\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch\",\"repo\":\"erigon\",\"chain\":\"sepolia\",\"branch\":\"main\",\"outcome\":\"failure\"}},{\"$project\":{\"date\":1,\"failure\":{\"$literal\":0}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"sync-from-scratch\",\n            repo: \"erigon\",\n            chain: \"sepolia\",\n            branch: \"main\",\n            outcome: \"failure\"\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            failure: { $literal: 0 },\n        }\n    }\n])\n"
    }
   ]
  },
  { "title": "Sync from scratch - Amoy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Sync time & dir size (main)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch\",\"repo\":\"erigon\",\"chain\":\"amoy\",\"branch\":\"main\"}},{\"$project\":{\"date\":1,\"total-sync-time_%\":\"$results.measures.total-sync-time_%\",\"dir-size-increment_%\":\"$results.measures.dir-size-increment_%\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"sync-from-scratch\",\n            repo: \"erigon\",\n            chain: \"amoy\",\n            branch: \"main\"\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'total-sync-time_%': '$results.measures.total-sync-time_%',\n            'dir-size-increment_%': '$results.measures.dir-size-increment_%'\n        }\n    }\n])\n"
    }
   ]
  },
  {
   "title": "Time to the tip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch\",\"repo\":\"erigon\",\"chain\":\"amoy\",\"branch\":\"main\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"time_difference_hours\":{\"$ifNull\":[{\"$round\":[{\"$divide\":[{\"$subtract\":[{\"$dateFromString\":{\"dateString\":\"$results.measures.sync-start-time\",\"format\":\"%Y-%m-%d %H:%M:%S\"}},{\"$dateFromString\":{\"dateString\":\"$results.measures.start-time\",\"format\":\"%Y-%m-%d %H:%M:%S\"}}]},3600000]},2]},0]}}}])",
     "query": "db.getCollection(\"TestResults\").aggregate([\n  {\n    $match: {\n      test: \"sync-from-scratch\",\n      repo: \"erigon\",\n      chain: \"amoy\",\n      branch: \"main\",\n      outcome: { $ne: \"failure\" },\n    }\n  },\n  {\n    $project: {\n      date: 1,\n      'time_difference_hours': {\n        $ifNull: [\n          {\n            $round: [\n              {\n                $divide: [\n                  { $subtract: [\n                    { $dateFromString: { dateString: \"$results.measures.sync-start-time\", format: \"%Y-%m-%d %H:%M:%S\" } },\n                    { $dateFromString: { dateString: \"$results.measures.start-time\", format: \"%Y-%m-%d %H:%M:%S\" } }\n                  ] },\n                  3600000 \n                ]\n              },\n              2 \n            ]\n          },\n          0 \n        ]\n      }\n    }\n  }\n])"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch\",\"repo\":\"erigon\",\"chain\":\"amoy\",\"branch\":\"main\"}},{\"$project\":{\"date\":1,\"failure\":{\"$ifNull\":[{\"$round\":[{\"$divide\":[{\"$subtract\":[{\"$dateFromString\":{\"dateString\":\"$results.measures.sync-start-time\",\"format\":\"%Y-%m-%d %H:%M:%S\"}},{\"$dateFromString\":{\"dateString\":\"$results.measures.start-time\",\"format\":\"%Y-%m-%d %H:%M:%S\"}}]},3600000]},2]},0]}}},{\"$match\":{\"failure\":0}}])",
     "query": "db.getCollection(\"TestResults\").aggregate([\n  {\n    $match: {\n      test: \"sync-from-scratch\",\n      repo: \"erigon\",\n      chain: \"amoy\",\n      branch: \"main\"\n    }\n  },\n  {\n    $project: {\n      date: 1,\n      'failure': {\n        $ifNull: [\n          {\n            $round: [\n              {\n                $divide: [\n                  { $subtract: [\n                    { $dateFromString: { dateString: \"$results.measures.sync-start-time\", format: \"%Y-%m-%d %H:%M:%S\" } },\n                    { $dateFromString: { dateString: \"$results.measures.start-time\", format: \"%Y-%m-%d %H:%M:%S\" } }\n                  ] },\n                  3600000\n                ]\n              },\n              2\n            ]\n          },\n          0\n        ]\n      }\n    }\n  },\n  {\n    $match: {\n      'failure': 0\n    }\n  }\n])"
    }
   ]
  },
  {
   "title": "Per block size (main)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"sync-from-scratch\",\"repo\":\"erigon\",\"chain\":\"amoy\",\"branch\":\"main\"}},{\"$project\":{\"date\":1,\"per-block-size-increment_mb\":\"$results.measures.per-block-size-increment_mb\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            test: \"sync-from-scratch\",\n            repo: \"erigon\",\n            chain: \"amoy\",\n            branch: \"main\"\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            'per-block-size-increment_mb': '$results.measures.per-block-size-increment_mb'\n        }\n    }\n])\n"
    }
   ]
  },
  { "title": "Snap Download", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "download time - branch main",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"snap-download\",\"branch\":\"main\",\"chain\":\"mainnet\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"total_download-time_m\":{\"$ifNull\":[\"$results.measures.total_download-time_m\",0]},\"indexing-time_m\":{\"$ifNull\":[\"$results.measures.indexing-time_m\",0]},\"blocks_snapshots\":{\"$ifNull\":[\"$results.measures.blocks-snapshots\",0]},\"rest_snapshots\":{\"$ifNull\":[\"$results.measures.rest-snapshots\",0]}}},{\"$project\":{\"date\":1,\"total_download-time_m\":1,\"indexing-time_m\":1}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n          test: \"snap-download\",\n          branch: \"main\",\n          chain: \"mainnet\",\n          outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            \"total_download-time_m\": {\n                $ifNull: [\"$results.measures.total_download-time_m\", 0]\n            },\n            \"indexing-time_m\": {\n                $ifNull: [\"$results.measures.indexing-time_m\", 0]\n            },\n            blocks_snapshots: {\n                $ifNull: [\"$results.measures.blocks-snapshots\", 0]\n            },\n            rest_snapshots: {\n                $ifNull: [\"$results.measures.rest-snapshots\", 0]\n            }\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            \"total_download-time_m\": 1,\n            \"indexing-time_m\": 1,\n            // blocks_snapshots: 1,\n            // rest_snapshots: 1,            \n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"snap-download\",\"branch\":\"main\",\"chain\":\"mainnet\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"blocks_snapshots\":\"$results.measures.blocks-snapshots\",\"state_snapshots\":\"$results.measures.rest-snapshots\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n          test: \"snap-download\",\n          branch: \"main\",\n          chain: \"mainnet\",\n          outcome: { $ne: \"failure\" },  \n        }\n    },\n    {\n        $project: {\n            date: 1,\n            blocks_snapshots: \"$results.measures.blocks-snapshots\",\n            state_snapshots: \"$results.measures.rest-snapshots\"\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"snap-download\",\"outcome\":\"failure\",\"branch\":\"main\",\"chain\":\"mainnet\"}},{\"$project\":{\"date\":1,\"total_download-time_m\":{\"$ifNull\":[\"$results.measures.total_download-time_m\",0]},\"blocks_snapshots\":{\"$ifNull\":[\"$results.measures.blocks-snapshots\",0]},\"rest_snapshots\":{\"$ifNull\":[\"$results.measures.rest-snapshots\",0]}}},{\"$project\":{\"date\":1,\"failure\":{\"$cond\":{\"if\":{\"$or\":[{\"$eq\":[{\"$add\":[\"$blocks_snapshots\",\"$rest_snapshots\"]},0]},{\"$eq\":[\"$total_download-time_m\",0]}]},\"then\":0,\"else\":{\"$divide\":[\"$total_download-time_m\",{\"$add\":[\"$blocks_snapshots\",\"$rest_snapshots\"]}]}}}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n          test: \"snap-download\",\n          outcome: \"failure\",\n          branch: \"main\",\n          chain: \"mainnet\"\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            \"total_download-time_m\": {\n                $ifNull: [\"$results.measures.total_download-time_m\", 0]\n            },\n            blocks_snapshots: {\n                $ifNull: [\"$results.measures.blocks-snapshots\", 0]\n            },\n            rest_snapshots: {\n                $ifNull: [\"$results.measures.rest-snapshots\", 0]\n            }\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            \"failure\": {\n                $cond: {\n                    if: {\n                        $or: [\n                            { $eq: [{ $add: [\"$blocks_snapshots\", \"$rest_snapshots\"] }, 0] },\n                            { $eq: [\"$total_download-time_m\", 0] }\n                        ]\n                    },\n                    then: 0,\n                    else: { $divide: [\"$total_download-time_m\", { $add: [\"$blocks_snapshots\", \"$rest_snapshots\"] }] }\n                }\n            }\n        }\n    }\n])\n"
    }
   ]
  },
  {
   "title": "download time - branch release/2.60",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"snap-download\",\"branch\":\"release/2.60\",\"chain\":\"mainnet\"}},{\"$project\":{\"date\":1,\"total_download-time_m\":{\"$ifNull\":[\"$results.measures.total_download-time_m\",0]},\"blocks_snapshots\":{\"$ifNull\":[\"$results.measures.blocks-snapshots\",0]},\"rest_snapshots\":{\"$ifNull\":[\"$results.measures.rest-snapshots\",0]}}},{\"$project\":{\"date\":1,\"total_download-time_m\":1,\"avg download time\":{\"$cond\":{\"if\":{\"$or\":[{\"$eq\":[{\"$add\":[\"$blocks_snapshots\",\"$rest_snapshots\"]},0]},{\"$eq\":[\"$total_download-time_m\",0]}]},\"then\":0,\"else\":{\"$divide\":[\"$total_download-time_m\",{\"$add\":[\"$blocks_snapshots\",\"$rest_snapshots\"]}]}}}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n          test: \"snap-download\",\n          branch: \"release/2.60\",\n          chain: \"mainnet\"\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            \"total_download-time_m\": {\n                $ifNull: [\"$results.measures.total_download-time_m\", 0]\n            },\n            blocks_snapshots: {\n                $ifNull: [\"$results.measures.blocks-snapshots\", 0]\n            },\n            rest_snapshots: {\n                $ifNull: [\"$results.measures.rest-snapshots\", 0]\n            }\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            \"total_download-time_m\": 1,\n            // blocks_snapshots: 1,\n            // rest_snapshots: 1,\n            \"avg download time\": {\n                $cond: {\n                    if: {\n                        $or: [\n                            { $eq: [{ $add: [\"$blocks_snapshots\", \"$rest_snapshots\"] }, 0] },\n                            { $eq: [\"$total_download-time_m\", 0] }\n                        ]\n                    },\n                    then: 0,\n                    else: { $divide: [\"$total_download-time_m\", { $add: [\"$blocks_snapshots\", \"$rest_snapshots\"] }] }\n                }\n            }\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"snap-download\",\"branch\":\"release/2.60\",\"chain\":\"mainnet\"}},{\"$project\":{\"date\":1,\"blocks_snapshots\":\"$results.measures.blocks-snapshots\",\"state_snapshots\":\"$results.measures.rest-snapshots\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n          test: \"snap-download\",\n          branch: \"release/2.60\",\n          chain: \"mainnet\"  \n        }\n    },\n    {\n        $project: {\n            date: 1,\n            blocks_snapshots: \"$results.measures.blocks-snapshots\",\n            state_snapshots: \"$results.measures.rest-snapshots\"\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"snap-download\",\"outcome\":\"failure\",\"branch\":\"release/2.60\",\"chain\":\"mainnet\"}},{\"$project\":{\"date\":1,\"total_download-time_m\":{\"$ifNull\":[\"$results.measures.total_download-time_m\",0]},\"blocks_snapshots\":{\"$ifNull\":[\"$results.measures.blocks-snapshots\",0]},\"rest_snapshots\":{\"$ifNull\":[\"$results.measures.rest-snapshots\",0]}}},{\"$project\":{\"date\":1,\"failure\":{\"$cond\":{\"if\":{\"$or\":[{\"$eq\":[{\"$add\":[\"$blocks_snapshots\",\"$rest_snapshots\"]},0]},{\"$eq\":[\"$total_download-time_m\",0]}]},\"then\":0,\"else\":{\"$divide\":[\"$total_download-time_m\",{\"$add\":[\"$blocks_snapshots\",\"$rest_snapshots\"]}]}}}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n          test: \"snap-download\",\n          outcome: \"failure\",\n          branch: \"release/2.60\",\n          chain: \"mainnet\"\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            \"total_download-time_m\": {\n                $ifNull: [\"$results.measures.total_download-time_m\", 0]\n            },\n            blocks_snapshots: {\n                $ifNull: [\"$results.measures.blocks-snapshots\", 0]\n            },\n            rest_snapshots: {\n                $ifNull: [\"$results.measures.rest-snapshots\", 0]\n            }\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            \"failure\": {\n                $cond: {\n                    if: {\n                        $or: [\n                            { $eq: [{ $add: [\"$blocks_snapshots\", \"$rest_snapshots\"] }, 0] },\n                            { $eq: [\"$total_download-time_m\", 0] }\n                        ]\n                    },\n                    then: 0,\n                    else: { $divide: [\"$total_download-time_m\", { $add: [\"$blocks_snapshots\", \"$rest_snapshots\"] }] }\n                }\n            }\n        }\n    }\n])\n"
    }
   ]
  },
  {
   "title": "download time per snapshot - branch main",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"snap-download\",\"branch\":\"main\",\"chain\":\"mainnet\",\"outcome\":{\"$ne\":\"failure\"}}},{\"$project\":{\"date\":1,\"total_download-time_m\":{\"$ifNull\":[\"$results.measures.total_download-time_m\",0]},\"indexing-time_m\":{\"$ifNull\":[\"$results.measures.indexing-time_m\",0]},\"blocks_snapshots\":{\"$ifNull\":[\"$results.measures.blocks-snapshots\",0]},\"rest_snapshots\":{\"$ifNull\":[\"$results.measures.rest-snapshots\",0]}}},{\"$project\":{\"date\":1,\"download time x snap\":{\"$cond\":{\"if\":{\"$or\":[{\"$eq\":[{\"$add\":[\"$blocks_snapshots\",\"$rest_snapshots\"]},0]},{\"$eq\":[\"$total_download-time_m\",0]}]},\"then\":0,\"else\":{\"$divide\":[\"$total_download-time_m\",{\"$add\":[\"$blocks_snapshots\",\"$rest_snapshots\"]}]}}},\"indexing time x snap\":{\"$cond\":{\"if\":{\"$or\":[{\"$eq\":[{\"$add\":[\"$blocks_snapshots\",\"$rest_snapshots\"]},0]},{\"$eq\":[\"$indexing-time_m\",0]}]},\"then\":0,\"else\":{\"$divide\":[\"$indexing-time_m\",{\"$add\":[\"$blocks_snapshots\",\"$rest_snapshots\"]}]}}}}}])",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n          test: \"snap-download\",\n          branch: \"main\",\n          chain: \"mainnet\",\n          outcome: { $ne: \"failure\" },\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            \"total_download-time_m\": {\n                $ifNull: [\"$results.measures.total_download-time_m\", 0]\n            },\n            \"indexing-time_m\": {\n                $ifNull: [\"$results.measures.indexing-time_m\", 0]\n            },\n            blocks_snapshots: {\n                $ifNull: [\"$results.measures.blocks-snapshots\", 0]\n            },\n            rest_snapshots: {\n                $ifNull: [\"$results.measures.rest-snapshots\", 0]\n            }\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            \"download time x snap\": {\n                $cond: {\n                    if: {\n                        $or: [\n                            { $eq: [{ $add: [\"$blocks_snapshots\", \"$rest_snapshots\"] }, 0] },\n                            { $eq: [\"$total_download-time_m\", 0] }\n                        ]\n                    },\n                    then: 0,\n                    else: { $divide: [\"$total_download-time_m\", { $add: [\"$blocks_snapshots\", \"$rest_snapshots\"] }] }\n                }\n            },\n            \"indexing time x snap\": {\n                $cond: {\n                    if: {\n                        $or: [\n                            { $eq: [{ $add: [\"$blocks_snapshots\", \"$rest_snapshots\"] }, 0] },\n                            { $eq: [\"$indexing-time_m\", 0] }\n                        ]\n                    },\n                    then: 0,\n                    else: { $divide: [\"$indexing-time_m\", { $add: [\"$blocks_snapshots\", \"$rest_snapshots\"] }] }\n                }\n            }\n        }\n    }\n])"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"snap-download\",\"outcome\":\"failure\",\"branch\":\"main\",\"chain\":\"mainnet\"}},{\"$project\":{\"date\":1,\"total_download-time_m\":{\"$ifNull\":[\"$results.measures.total_download-time_m\",0]},\"blocks_snapshots\":{\"$ifNull\":[\"$results.measures.blocks-snapshots\",0]},\"rest_snapshots\":{\"$ifNull\":[\"$results.measures.rest-snapshots\",0]}}},{\"$project\":{\"date\":1,\"failure\":{\"$cond\":{\"if\":{\"$or\":[{\"$eq\":[{\"$add\":[\"$blocks_snapshots\",\"$rest_snapshots\"]},0]},{\"$eq\":[\"$total_download-time_m\",0]}]},\"then\":0,\"else\":{\"$divide\":[\"$total_download-time_m\",{\"$add\":[\"$blocks_snapshots\",\"$rest_snapshots\"]}]}}}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n          test: \"snap-download\",\n          outcome: \"failure\",\n          branch: \"main\",\n          chain: \"mainnet\"\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            \"total_download-time_m\": {\n                $ifNull: [\"$results.measures.total_download-time_m\", 0]\n            },\n            blocks_snapshots: {\n                $ifNull: [\"$results.measures.blocks-snapshots\", 0]\n            },\n            rest_snapshots: {\n                $ifNull: [\"$results.measures.rest-snapshots\", 0]\n            }\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            \"failure\": {\n                $cond: {\n                    if: {\n                        $or: [\n                            { $eq: [{ $add: [\"$blocks_snapshots\", \"$rest_snapshots\"] }, 0] },\n                            { $eq: [\"$total_download-time_m\", 0] }\n                        ]\n                    },\n                    then: 0,\n                    else: { $divide: [\"$total_download-time_m\", { $add: [\"$blocks_snapshots\", \"$rest_snapshots\"] }] }\n                }\n            }\n        }\n    }\n])\n"
    }
   ]
  },
  {
   "title": "download time - branch release/2.61",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"snap-download\",\"branch\":\"release/2.61\",\"chain\":\"mainnet\"}},{\"$project\":{\"date\":1,\"total_download-time_m\":{\"$ifNull\":[\"$results.measures.total_download-time_m\",0]},\"blocks_snapshots\":{\"$ifNull\":[\"$results.measures.blocks-snapshots\",0]},\"rest_snapshots\":{\"$ifNull\":[\"$results.measures.rest-snapshots\",0]}}},{\"$project\":{\"date\":1,\"total_download-time_m\":1,\"avg download time\":{\"$cond\":{\"if\":{\"$or\":[{\"$eq\":[{\"$add\":[\"$blocks_snapshots\",\"$rest_snapshots\"]},0]},{\"$eq\":[\"$total_download-time_m\",0]}]},\"then\":0,\"else\":{\"$divide\":[\"$total_download-time_m\",{\"$add\":[\"$blocks_snapshots\",\"$rest_snapshots\"]}]}}}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n          test: \"snap-download\",\n          branch: \"release/2.61\",\n          chain: \"mainnet\"\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            \"total_download-time_m\": {\n                $ifNull: [\"$results.measures.total_download-time_m\", 0]\n            },\n            blocks_snapshots: {\n                $ifNull: [\"$results.measures.blocks-snapshots\", 0]\n            },\n            rest_snapshots: {\n                $ifNull: [\"$results.measures.rest-snapshots\", 0]\n            }\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            \"total_download-time_m\": 1,\n            // blocks_snapshots: 1,\n            // rest_snapshots: 1,\n            \"avg download time\": {\n                $cond: {\n                    if: {\n                        $or: [\n                            { $eq: [{ $add: [\"$blocks_snapshots\", \"$rest_snapshots\"] }, 0] },\n                            { $eq: [\"$total_download-time_m\", 0] }\n                        ]\n                    },\n                    then: 0,\n                    else: { $divide: [\"$total_download-time_m\", { $add: [\"$blocks_snapshots\", \"$rest_snapshots\"] }] }\n                }\n            }\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"snap-download\",\"branch\":\"release/2.61\",\"chain\":\"mainnet\"}},{\"$project\":{\"date\":1,\"blocks_snapshots\":\"$results.measures.blocks-snapshots\",\"state_snapshots\":\"$results.measures.rest-snapshots\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n          test: \"snap-download\",\n          branch: \"release/2.61\",\n          chain: \"mainnet\"  \n        }\n    },\n    {\n        $project: {\n            date: 1,\n            blocks_snapshots: \"$results.measures.blocks-snapshots\",\n            state_snapshots: \"$results.measures.rest-snapshots\"\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"snap-download\",\"outcome\":\"failure\",\"branch\":\"release/2.61\",\"chain\":\"mainnet\"}},{\"$project\":{\"date\":1,\"total_download-time_m\":{\"$ifNull\":[\"$results.measures.total_download-time_m\",0]},\"blocks_snapshots\":{\"$ifNull\":[\"$results.measures.blocks-snapshots\",0]},\"rest_snapshots\":{\"$ifNull\":[\"$results.measures.rest-snapshots\",0]}}},{\"$project\":{\"date\":1,\"failure\":{\"$cond\":{\"if\":{\"$or\":[{\"$eq\":[{\"$add\":[\"$blocks_snapshots\",\"$rest_snapshots\"]},0]},{\"$eq\":[\"$total_download-time_m\",0]}]},\"then\":0,\"else\":{\"$divide\":[\"$total_download-time_m\",{\"$add\":[\"$blocks_snapshots\",\"$rest_snapshots\"]}]}}}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n          test: \"snap-download\",\n          outcome: \"failure\",\n          branch: \"release/2.61\",\n          chain: \"mainnet\"\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            \"total_download-time_m\": {\n                $ifNull: [\"$results.measures.total_download-time_m\", 0]\n            },\n            blocks_snapshots: {\n                $ifNull: [\"$results.measures.blocks-snapshots\", 0]\n            },\n            rest_snapshots: {\n                $ifNull: [\"$results.measures.rest-snapshots\", 0]\n            }\n        }\n    },\n    {\n        $project: {\n            date: 1,\n            \"failure\": {\n                $cond: {\n                    if: {\n                        $or: [\n                            { $eq: [{ $add: [\"$blocks_snapshots\", \"$rest_snapshots\"] }, 0] },\n                            { $eq: [\"$total_download-time_m\", 0] }\n                        ]\n                    },\n                    then: 0,\n                    else: { $divide: [\"$total_download-time_m\", { $add: [\"$blocks_snapshots\", \"$rest_snapshots\"] }] }\n                }\n            }\n        }\n    }\n])\n"
    }
   ]
  },
  { "title": "Clean exit", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 134 } },
  {
   "title": "Clean exit block downloading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"clean-exit-block-downloading\"}},{\"$project\":{\"outcome\":\"$results.outcome\",\"exit time\":{\"$ifNull\":[\"$results.measures.exit_time_secs\",0]},\"date\":\"$date\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n          test: \"clean-exit-block-downloading\"      \n        }\n    },\n    {\n        $project: {\n            outcome: \"$results.outcome\",\n            \"exit time\": {\n                $ifNull: [\"$results.measures.exit_time_secs\", 0]\n            },\n            date: \"$date\"\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"clean-exit-block-downloading\",\"results.outcome\":\"FAILURE\"}},{\"$project\":{\"outcome\":\"$results.outcome\",\"failure\":{\"$ifNull\":[\"$results.measures.exit_time_secs\",0]},\"date\":\"$date\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n          test: \"clean-exit-block-downloading\",\n          \"results.outcome\": \"FAILURE\",\n        }\n    },\n    {\n        $project: {\n            outcome: \"$results.outcome\",\n            \"failure\": {\n                $ifNull: [\"$results.measures.exit_time_secs\", 0]\n            },\n            date: \"$date\"\n        }\n    }\n])\n"
    }
   ]
  },
  {
   "title": "Clean exit snapshot downloading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"clean-exit-snapshot-downloading\"}},{\"$project\":{\"outcome\":\"$results.outcome\",\"exit time\":{\"$ifNull\":[\"$results.measures.exit_time_secs\",0]},\"date\":\"$date\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n          test: \"clean-exit-snapshot-downloading\"      \n        }\n    },\n    {\n        $project: {\n            outcome: \"$results.outcome\",\n            \"exit time\": {\n                $ifNull: [\"$results.measures.exit_time_secs\", 0]\n            },\n            date: \"$date\"\n        }\n    }\n])\n"
    },
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"test\":\"clean-exit-snapshot-downloading\",\"results.outcome\":\"FAILURE\"}},{\"$project\":{\"outcome\":\"$results.outcome\",\"failure\":{\"$ifNull\":[\"$results.measures.exit_time_secs\",0]},\"date\":\"$date\"}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n          test: \"clean-exit-snapshot-downloading\",  \n          \"results.outcome\": \"FAILURE\",\n        }\n    },\n    {\n        $project: {\n            outcome: \"$results.outcome\",\n            \"failure\": {\n                $ifNull: [\"$results.measures.exit_time_secs\", 0]\n            },\n            date: \"$date\"\n        }\n    }\n])\n"
    }
   ]
  },
  { "title": "Silkworm - eth_call", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 143 } },
  {
   "title": "Latency QPS 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_call\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_call\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
    }
   ]
  },
  {
   "title": "Latency QPS 100",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 144 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_call\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_call\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
    }
   ]
  },
  {
   "title": "Latency QPS 1000",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_call\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_call\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
    }
   ]
  },
  {
   "title": "Latency QPS 10000",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_call\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_call\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
    }
   ]
  },
  {
   "title": "Latency QPS 20000",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_call\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_call\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
    }
   ]
  },
  {
   "title": "Silkworm - eth_getLogs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency QPS 1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8268 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getLogs\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getLogs\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    },
    {
     "title": "Latency QPS 100",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8268 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getLogs\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getLogs\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    },
    {
     "title": "Latency QPS 1000",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8276 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getLogs\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getLogs\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    },
    {
     "title": "Latency QPS 10000",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8276 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getLogs\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getLogs\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    },
    {
     "title": "Latency QPS 20000",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8284 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getLogs\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getLogs\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    }
   ]
  },
  { "title": "Silkworm - eth_getBalance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 169 } },
  {
   "title": "Latency QPS 1",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getBalance\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getBalance\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
    }
   ]
  },
  {
   "title": "Latency QPS 100",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getBalance\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getBalance\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
    }
   ]
  },
  {
   "title": "Latency QPS 1000",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getBalance\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getBalance\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
    }
   ]
  },
  {
   "title": "Latency QPS 10000",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getBalance\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getBalance\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
    }
   ]
  },
  {
   "title": "Latency QPS 20000",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getBalance\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
     "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getBalance\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
    }
   ]
  },
  {
   "title": "Silkworm - eth_getBlockByHash",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 194 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency QPS 1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8267 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getBlockByHash\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getBlockByHash\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    },
    {
     "title": "Latency QPS 100",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8267 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getBlockByHash\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getBlockByHash\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    },
    {
     "title": "Latency QPS 1000",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8275 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getBlockByHash\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getBlockByHash\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    },
    {
     "title": "Latency QPS 10000",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8275 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getBlockByHash\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getBlockByHash\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Silkworm - eth_getBlockByNumber",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 195 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency QPS 1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8269 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getBlockByNumber\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getBlockByNumber\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    },
    {
     "title": "Latency QPS 100",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8269 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getBlockByNumber\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getBlockByNumber\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    },
    {
     "title": "Latency QPS 1000",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8277 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getBlockByNumber\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getBlockByNumber\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    },
    {
     "title": "Latency QPS 10000",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8277 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getBlockByNumber\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getBlockByNumber\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Silkworm - eth_getTransactionByHash",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 196 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency QPS 1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8268 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getTransactionByHash\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getTransactionByHash\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    },
    {
     "title": "Latency QPS 100",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8268 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getTransactionByHash\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getTransactionByHash\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    },
    {
     "title": "Latency QPS 1000",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8276 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getTransactionByHash\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getTransactionByHash\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    },
    {
     "title": "Latency QPS 10000",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8276 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getTransactionByHash\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getTransactionByHash\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Silkworm - eth_getTransactionReceipt",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 197 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency QPS 1",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8267 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getTransactionReceipt\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",0]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getTransactionReceipt\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 0] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    },
    {
     "title": "Latency QPS 100",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8267 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getTransactionReceipt\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",1]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getTransactionReceipt\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 1] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    },
    {
     "title": "Latency QPS 1000",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8275 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getTransactionReceipt\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",2]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getTransactionReceipt\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 2] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    },
    {
     "title": "Latency QPS 10000",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8275 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getTransactionReceipt\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",3]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getTransactionReceipt\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 3] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    },
    {
     "title": "Latency QPS 20000",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8283 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "parsedQuery": "db.getCollection(\"TestResults\").aggregate([{\"$match\":{\"repo\":\"silkworm\",\"branch\":\"master\",\"chain\":\"mainnet\",\"test\":\"rpc-performance-test-erigon-eth_getTransactionReceipt\"}},{\"$project\":{\"date\":1,\"Latency (repetition 0)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",0]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 1)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",1]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 2)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",2]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 3)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",3]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}},\"Latency (repetition 4)\":{\"$let\":{\"vars\":{\"firstResult\":{\"$arrayElemAt\":[\"$results.results\",4]}},\"in\":{\"$let\":{\"vars\":{\"firstTestRepetition\":{\"$arrayElemAt\":[\"$$firstResult.testRepetitions\",4]}},\"in\":\"$$firstTestRepetition.vegetaReport.latencies.max\"}}}}}}])\n",
       "query": "db.getCollection(\"TestResults\").aggregate([\n    {\n        $match: {\n            repo: \"silkworm\",\n            branch: \"master\",\n            chain: \"mainnet\",\n            test: \"rpc-performance-test-erigon-eth_getTransactionReceipt\"\n        }\n    },\n  {\n    $project: {\n      date: 1,\n      \"Latency (repetition 0)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 0] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 1)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 1] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 2)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 2] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 3)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 3] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      },\n      \"Latency (repetition 4)\": {\n        $let: {\n          vars: {\n            firstResult: { $arrayElemAt: ['$results.results', 4] }\n          },\n          in: {\n            $let: {\n              vars: {\n                firstTestRepetition: { $arrayElemAt: ['$$firstResult.testRepetitions', 4] }\n              },\n              in: '$$firstTestRepetition.vegetaReport.latencies.max'\n            }\n          }\n        }\n      }\n    }\n  }\n])\n"
      }
     ]
    }
   ]
  }
 ]
}