---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: erigon
  name: eth66-peering-tcp
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: eth66-pr-tcp
      port: 30303
      protocol: TCP
      targetPort: 30303
  selector:
    app: erigon
  type: LoadBalancer
