---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: erigon
  name: metrics
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: metrics
      port: 6060
      protocol: TCP
      targetPort: 6060
  selector:
    app: erigon
