# prometheus.yml
global:
  scrape_interval: 10s
  scrape_timeout: 3s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'erigon-serial'
    static_configs:
      - targets: ['host.docker.internal:6061']
    metrics_path: /debug/metrics/prometheus

  - job_name: 'erigon-par'
    static_configs:
      - targets: ['host.docker.internal:6062']
    metrics_path: /debug/metrics/prometheus

