name: Cleanup runner disk space
description: Remove large pre-installed packages to free disk space on GitHub-hosted runners

runs:
  using: composite
  steps:
    - name: Cleanup space
      if: runner.os == 'Linux'
      shell: bash
      run: |
        rm -fr /opt/az \
               /opt/microsoft \
               /usr/share/dotnet \
               /usr/share/miniconda \
               /usr/share/swift
    - name: Show disk usage
      shell: bash
      run: df -h
