name: Restore Go build cache
description: Restore Go build cache with a tagged key

inputs:
  buildtag:
    description: "Build cache tag (e.g. plain, race, coverage)"
    required: true
  build:
    description: "GOCACHE path (from setup-go outputs)"
    required: true
  goversion:
    description: "Go version string (from setup-go outputs)"
    required: true

runs:
  using: composite
  steps:
    - uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.build }}
        key: gocache-${{ inputs.buildtag }}-${{ inputs.goversion }}-${{ runner.os }}-${{ runner.arch }}-${{ github.run_id }}
        restore-keys: gocache-${{ inputs.buildtag }}-${{ inputs.goversion }}-${{ runner.os }}-${{ runner.arch }}-
