name: Restore Go build cache
description: Restore Go build cache keyed by workflow, job, and run

inputs:
  gocache:
    description: "GOCACHE path"
    required: true
  goversion:
    description: "Full Go version string (e.g. go1.25.7)"
    required: true
  workflow:
    description: "Workflow name for cache key namespacing"
    required: true
  extra-key:
    description: "Extra segment appended after runner.arch in the cache key (e.g. matrix value)"
    required: false
    default: ''

outputs:
  cache-matched-key:
    description: "The cache key that was restored (empty if miss)"
    value: ${{ steps.restore.outputs.cache-matched-key }}
  cache-key:
    description: "The primary cache key (for use by save-build-cache)"
    value: gocache|${{ inputs.workflow }}|${{ github.job }}|${{ inputs.extra-key }}|${{ inputs.goversion }}|${{ runner.os }}|${{ runner.arch }}|${{ github.run_id }}|${{ github.run_attempt }}

runs:
  using: composite
  steps:
    - id: restore
      uses: actions/cache/restore@v4
      with:
        path: ${{ inputs.gocache }}
        key: gocache|${{ inputs.workflow }}|${{ github.job }}|${{ inputs.extra-key }}|${{ inputs.goversion }}|${{ runner.os }}|${{ runner.arch }}|${{ github.run_id }}|${{ github.run_attempt }}
        restore-keys: |
          gocache|${{ inputs.workflow }}|${{ github.job }}|${{ inputs.extra-key }}|${{ inputs.goversion }}|${{ runner.os }}|${{ runner.arch }}|${{ github.run_id }}|
          gocache|${{ inputs.workflow }}|${{ github.job }}|${{ inputs.extra-key }}|${{ inputs.goversion }}|${{ runner.os }}|${{ runner.arch }}|

    - name: Warn on build cache miss
      if: ${{ steps.restore.outputs.cache-matched-key == '' }}
      shell: bash
      run: echo "::warning::Go build cache miss — no matching key found"
