// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/erigontech/erigon/polygon/bor (interfaces: bridgeReader)
//
// Generated by this command:
//
//	mockgen -typed=true -destination=./bridge_reader_mock.go -package=bor . bridgeReader
//

// Package bor is a generated GoMock package.
package bor

import (
	context "context"
	reflect "reflect"
	time "time"

	common "github.com/erigontech/erigon-lib/common"
	types "github.com/erigontech/erigon/execution/types"
	gomock "go.uber.org/mock/gomock"
)

// MockbridgeReader is a mock of bridgeReader interface.
type MockbridgeReader struct {
	ctrl     *gomock.Controller
	recorder *MockbridgeReaderMockRecorder
	isgomock struct{}
}

// MockbridgeReaderMockRecorder is the mock recorder for MockbridgeReader.
type MockbridgeReaderMockRecorder struct {
	mock *MockbridgeReader
}

// NewMockbridgeReader creates a new mock instance.
func NewMockbridgeReader(ctrl *gomock.Controller) *MockbridgeReader {
	mock := &MockbridgeReader{ctrl: ctrl}
	mock.recorder = &MockbridgeReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockbridgeReader) EXPECT() *MockbridgeReaderMockRecorder {
	return m.recorder
}

// Events mocks base method.
func (m *MockbridgeReader) Events(ctx context.Context, blockHash common.Hash, blockNum uint64) ([]*types.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events", ctx, blockHash, blockNum)
	ret0, _ := ret[0].([]*types.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Events indicates an expected call of Events.
func (mr *MockbridgeReaderMockRecorder) Events(ctx, blockHash, blockNum any) *MockbridgeReaderEventsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockbridgeReader)(nil).Events), ctx, blockHash, blockNum)
	return &MockbridgeReaderEventsCall{Call: call}
}

// MockbridgeReaderEventsCall wrap *gomock.Call
type MockbridgeReaderEventsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockbridgeReaderEventsCall) Return(arg0 []*types.Message, arg1 error) *MockbridgeReaderEventsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockbridgeReaderEventsCall) Do(f func(context.Context, common.Hash, uint64) ([]*types.Message, error)) *MockbridgeReaderEventsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockbridgeReaderEventsCall) DoAndReturn(f func(context.Context, common.Hash, uint64) ([]*types.Message, error)) *MockbridgeReaderEventsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// EventsWithinTime mocks base method.
func (m *MockbridgeReader) EventsWithinTime(ctx context.Context, timeFrom, timeTo time.Time) ([]*types.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EventsWithinTime", ctx, timeFrom, timeTo)
	ret0, _ := ret[0].([]*types.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EventsWithinTime indicates an expected call of EventsWithinTime.
func (mr *MockbridgeReaderMockRecorder) EventsWithinTime(ctx, timeFrom, timeTo any) *MockbridgeReaderEventsWithinTimeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EventsWithinTime", reflect.TypeOf((*MockbridgeReader)(nil).EventsWithinTime), ctx, timeFrom, timeTo)
	return &MockbridgeReaderEventsWithinTimeCall{Call: call}
}

// MockbridgeReaderEventsWithinTimeCall wrap *gomock.Call
type MockbridgeReaderEventsWithinTimeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockbridgeReaderEventsWithinTimeCall) Return(arg0 []*types.Message, arg1 error) *MockbridgeReaderEventsWithinTimeCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockbridgeReaderEventsWithinTimeCall) Do(f func(context.Context, time.Time, time.Time) ([]*types.Message, error)) *MockbridgeReaderEventsWithinTimeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockbridgeReaderEventsWithinTimeCall) DoAndReturn(f func(context.Context, time.Time, time.Time) ([]*types.Message, error)) *MockbridgeReaderEventsWithinTimeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
