#!/bin/bash
# Docker hub does a recursive clone, then checks the branch out,
# so when a PR adds a submodule (or updates it), it fails.
git status
ls .git
git submodule update --init --recursive --force
ls .git/modules/
ls ./libmdbx/.git
ls .git/modules/libmdbx
