---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: erigon
  name: erigon
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: erigon
  serviceName: erigon
  template:
    metadata:
      labels:
        app: erigon
    spec:
      containers:
        - args: []
          command:
            - erigon
          env: []
          image: erigontech/erigon
          name: erigon
          ports:
            - containerPort: 9090
              name: private-api
            - containerPort: 8551
              name: engine
            - containerPort: 30303
              name: eth66-pr-tcp
              protocol: TCP
            - containerPort: 30303
              name: eth66-pr-udp
              protocol: UDP
            - containerPort: 8545
              name: http
              protocol: TCP
            - containerPort: 6060
              name: metrics
            - containerPort: 6070
              name: pprof
            - containerPort: 42069
              name: snap-sync-tcp
              protocol: TCP
            - containerPort: 42069
              name: snap-sync-udp
              protocol: UDP
          readinessProbe:
            tcpSocket:
              port: 8545
          resources:
            requests:
              cpu: 2462m
              memory: 16Gi
          securityContext:
            allowPrivilegeEscalation: false
            runAsGroup: 1000
            runAsUser: 1000
          volumeMounts: []
      initContainers: []
      volumes: []
  volumeClaimTemplates: []