PRESET_BASE: minimal
MIN_GENESIS_TIME: 1785105479
SECONDS_PER_SLOT: 6
ALTAIR_FORK_EPOCH: 0
BELLATRIX_FORK_EPOCH: 0
CAPELLA_FORK_EPOCH: 0
DENEB_FORK_EPOCH: 0
ELECTRA_FORK_EPOCH: 0
FULU_FORK_EPOCH: 0
TERMINAL_TOTAL_DIFFICULTY: 0
