// Code generated by execution/vm/gen from run.go. DO NOT EDIT.

package vm

import (
	"errors"
	"fmt"

	"github.com/erigontech/erigon/common/dbg"
	"github.com/erigontech/erigon/common/math"
	"github.com/erigontech/erigon/execution/protocol/mdgas"
	"github.com/erigontech/erigon/execution/protocol/params"
	"github.com/erigontech/erigon/execution/tracing"
)

func (evm *EVM) runTraced(contract Contract, gas mdgas.MdGas, input []byte, readOnly, debug, trace bool) (ret []byte, gasRemaining mdgas.MdGas, gasUsed mdgas.MdGasUsage, err error) {

	if len(contract.Code) == 0 {
		return nil, gas, mdgas.MdGasUsage{}, nil
	}

	evm.returnData = nil

	var (
		op          OpCode
		callContext = getCallContext(contract, input, gas)

		pc   = uint64(0)
		cost mdgas.MdGasCost

		pcCopy  uint64
		oldGas  mdgas.MdGas
		callGas mdgas.MdGasCost
		logged  bool
		res     []byte
		tracer  = evm.config.Tracer
	)

	restoreReadonly := readOnly && !evm.readOnly
	if restoreReadonly {
		evm.readOnly = true
	}

	evm.depth++
	defer func() {

		gasUsed.StateSpill = callContext.stateGasSpill
		gasUsed.State = int64(gas.State) - int64(callContext.stateGas) + int64(callContext.stateGasSpill)
		callContext.put()
		if restoreReadonly {
			evm.readOnly = false
		}
		evm.depth--
	}()

	if true && debug {
		defer func() {
			if err == nil {
				return
			}
			switch {
			case !logged && tracer.HasOpcodeHook() && tracer.WantsOpcode(byte(op)):
				tracer.EmitOpcode(pcCopy, byte(op), oldGas, cost, callContext, evm.returnData, evm.depth, VMErrorFromErr(err))
			case tracer.HasOpcodeHook() && tracer.HasFaultHook():
				tracer.EmitFault(pcCopy, byte(op), oldGas, cost, callContext, evm.depth, VMErrorFromErr(err))
			}
		}()
	}

	stack := &callContext.Stack
	jt := evm.jt

run:
	for {
		op = contract.GetOp(pc)

		if !true {
			sLen, gas := stack.len(), callContext.gas
			switch op {

			case PUSH1:
				if sLen < stackLimit && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					pc, _, _ = opPush1(pc, evm, callContext)
					pc++
					continue
				}
			case PUSH2:
				if sLen < stackLimit && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					pc, _, _ = opPush2(pc, evm, callContext)
					pc++
					continue
				}
			case ADD:
				if sLen >= 2 && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					x, y := stack.pop1Peek1()
					y.Add(x, y)
					pc++
					continue
				}
			case POP:
				if sLen >= 1 && gas >= GasQuickStep {
					callContext.gas = gas - GasQuickStep
					stack.drop()
					pc++
					continue
				}
			case JUMPDEST:
				if gas >= params.JumpdestGas {
					callContext.gas = gas - params.JumpdestGas
					pc++
					continue
				}
			case JUMP:
				if sLen >= 1 && gas >= GasMidStep {
					callContext.gas = gas - GasMidStep
					if pc, res, err = opJump(pc, evm, callContext); err != nil {
						break run
					}
					pc++
					continue
				}
			case JUMPI:
				if sLen >= 2 && gas >= GasSlowStep {
					callContext.gas = gas - GasSlowStep
					if pc, res, err = opJumpi(pc, evm, callContext); err != nil {
						break run
					}
					pc++
					continue
				}
			case SUB:
				if sLen >= 2 && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					_, _, _ = opSub(pc, evm, callContext)
					pc++
					continue
				}
			case MUL:
				if sLen >= 2 && gas >= GasFastStep {
					callContext.gas = gas - GasFastStep
					_, _, _ = opMul(pc, evm, callContext)
					pc++
					continue
				}
			case DIV:
				if sLen >= 2 && gas >= GasFastStep {
					callContext.gas = gas - GasFastStep
					_, _, _ = opDiv(pc, evm, callContext)
					pc++
					continue
				}
			case LT:
				if sLen >= 2 && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					_, _, _ = opLt(pc, evm, callContext)
					pc++
					continue
				}
			case GT:
				if sLen >= 2 && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					_, _, _ = opGt(pc, evm, callContext)
					pc++
					continue
				}
			case EQ:
				if sLen >= 2 && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					_, _, _ = opEq(pc, evm, callContext)
					pc++
					continue
				}
			case AND:
				if sLen >= 2 && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					_, _, _ = opAnd(pc, evm, callContext)
					pc++
					continue
				}
			case ISZERO:
				if sLen >= 1 && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					_, _, _ = opIszero(pc, evm, callContext)
					pc++
					continue
				}
			case DUP1:
				if sLen >= 1 && sLen < stackLimit && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					stack.dup(0)
					pc++
					continue
				}
			case DUP2:
				if sLen >= 2 && sLen < stackLimit && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					stack.dup(1)
					pc++
					continue
				}
			case DUP3:
				if sLen >= 3 && sLen < stackLimit && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					stack.dup(2)
					pc++
					continue
				}
			case DUP4:
				if sLen >= 4 && sLen < stackLimit && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					stack.dup(3)
					pc++
					continue
				}
			case DUP5:
				if sLen >= 5 && sLen < stackLimit && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					stack.dup(4)
					pc++
					continue
				}
			case DUP6:
				if sLen >= 6 && sLen < stackLimit && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					stack.dup(5)
					pc++
					continue
				}
			case DUP7:
				if sLen >= 7 && sLen < stackLimit && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					stack.dup(6)
					pc++
					continue
				}
			case DUP8:
				if sLen >= 8 && sLen < stackLimit && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					stack.dup(7)
					pc++
					continue
				}
			case SWAP1:
				if sLen >= 2 && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					stack.swap(1)
					pc++
					continue
				}
			case SWAP2:
				if sLen >= 3 && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					stack.swap(2)
					pc++
					continue
				}
			case SWAP3:
				if sLen >= 4 && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					stack.swap(3)
					pc++
					continue
				}
			case SWAP4:
				if sLen >= 5 && gas >= GasFastestStep {
					callContext.gas = gas - GasFastestStep
					stack.swap(4)
					pc++
					continue
				}

			}
		}
		callContext.cacheGen++
		if true && debug {

			logged = false
			pcCopy = pc
			oldGas = callContext.Gas()
		}

		operation := &jt[op]
		cost = mdgas.MdGasCost{Execution: operation.constantGas}

		if sLen := stack.len(); uint(sLen-operation.numPop) > uint(operation.maxStack-operation.numPop) {
			return nil, callContext.Gas(), mdgas.MdGasUsage{}, stackBoundsErr(sLen, operation)
		}

		if callContext.gas < cost.Execution {
			return nil, callContext.Gas(), mdgas.MdGasUsage{}, ErrOutOfGas
		} else {
			callContext.gas -= cost.Execution
		}

		var memorySize uint64
		if operation.dynamicGas != nil {

			if operation.memorySize != nil {
				memSize, overflow := operation.memorySize(callContext)
				if overflow {
					return nil, callContext.Gas(), mdgas.MdGasUsage{}, ErrGasUintOverflow
				}

				if memorySize, overflow = math.SafeMul(ToWordSize(memSize), 32); overflow {
					return nil, callContext.Gas(), mdgas.MdGasUsage{}, ErrGasUintOverflow
				}
			}

			evm.callGasTemp = 0

			var dynamicCost mdgas.MdGasCost
			dynamicCost, err = operation.dynamicGas(evm, callContext, callContext.Gas(), memorySize)
			if err != nil {
				if !errors.Is(err, ErrOutOfGas) {
					err = fmt.Errorf("%w: %w", ErrOutOfGas, err)
				}
				return nil, callContext.Gas(), mdgas.MdGasUsage{}, err
			}
			if true {
				cost = cost.Plus(dynamicCost)
				callGas = cost
				callGas.Execution -= evm.CallGasTemp()
				if dbg.TraceDynamicGas && dynamicCost != (mdgas.MdGasCost{}) {
					gasCost := traceGas(op, callGas, cost)
					fmt.Printf("%d (%d.%d) Dynamic Gas: %d %d (%s)\n", evm.intraBlockState.BlockNumber(), evm.intraBlockState.TxIndex(), evm.intraBlockState.Incarnation(), gasCost.Execution, gasCost.State, op)
				}
			}
			if callContext.gas < dynamicCost.Execution {
				return nil, callContext.Gas(), mdgas.MdGasUsage{}, ErrOutOfGas
			}
			callContext.gas -= dynamicCost.Execution
			if dynamicCost.State > 0 {
				ok := callContext.useMdGas(uint64(dynamicCost.State), mdgas.StateGas, nil, tracing.GasChangeIgnored)
				if !ok {
					return nil, callContext.Gas(), mdgas.MdGasUsage{}, ErrOutOfGas
				}
			} else if dynamicCost.State < 0 {
				callContext.refillStateGas(uint64(-dynamicCost.State), nil, tracing.GasChangeIgnored)
			}
		}

		if true && debug {
			if tracer.HasGasChangeHook() {
				tracer.EmitGasChange(oldGas, callContext.Gas(), tracing.GasChangeCallOpCode)
			}
			if tracer.HasOpcodeHook() && tracer.WantsOpcode(byte(op)) {
				tracer.EmitOpcode(pc, byte(op), oldGas, cost, callContext, evm.returnData, evm.depth, VMErrorFromErr(err))
				logged = true
			}
		}

		if memorySize > 0 {
			callContext.Memory.Resize(memorySize)
		}

		if true && trace {
			var opstr string
			if operation.string != nil {
				opstr = operation.string(pc, callContext)
			} else {
				opstr = op.String()
			}

			gasCost := traceGas(op, callGas, cost)
			fmt.Printf("%d (%d.%d) %5d %5d %5d %s\n", evm.intraBlockState.BlockNumber(), evm.intraBlockState.TxIndex(), evm.intraBlockState.Incarnation(), pc, gasCost.Execution, gasCost.State, opstr)
		}

		pc, res, err = operation.execute(pc, evm, callContext)
		if err != nil {
			break
		}
		pc++
	}

	if errors.Is(err, errStopToken) {
		err = nil
	}

	return res, callContext.Gas(), mdgas.MdGasUsage{}, err
}
