name: Save Go build cache
description: Save Go build cache with a tagged key

inputs:
  buildtag:
    description: "Build cache tag (e.g. plain, race, coverage)"
    required: true
  build:
    description: "GOCACHE path (from setup-go outputs)"
    required: true
  goversion:
    description: "Go version string (from setup-go outputs)"
    required: true

runs:
  using: composite
  steps:
    - name: Show build cache size
      if: ${{ always() }}
      shell: bash
      run: du -hs '${{ inputs.build }}' || true

    - name: Clean non-deterministic cache metadata
      if: ${{ always() }}
      shell: bash
      run: rm -f '${{ inputs.build }}/trim.txt' '${{ inputs.build }}/testexpire.txt'

    - name: Hash build cache contents
      id: cache-hash
      if: ${{ always() }}
      shell: bash
      run: |
        hash=$(cd '${{ inputs.build }}' && find . -type f | sort | sha256sum | cut -d' ' -f1)
        echo "hash=$hash" >> "$GITHUB_OUTPUT"

    - uses: actions/cache/save@v4
      if: ${{ always() }}
      with:
        path: ${{ inputs.build }}
        key: gocache-${{ inputs.buildtag }}-${{ inputs.goversion }}-${{ runner.os }}-${{ runner.arch }}-${{ steps.cache-hash.outputs.hash }}
