name: Save Go build cache
description: Save Go build cache keyed by workflow, job, and branch

runs:
  using: composite
  steps:
    - name: Validate required env vars
      shell: bash
      run: |
        : "${ERIGON_CI_GOCACHE:?must be set by setup-erigon}"
        : "${ERIGON_CI_GOVERSION:?must be set by setup-erigon}"
        : "${ERIGON_CI_WORKFLOW:?must be set by setup-erigon}"

    - name: Show build cache size
      if: ${{ always() }}
      shell: bash
      run: du -hs "$ERIGON_CI_GOCACHE" || true

    - name: Clean fuzz cache
      if: ${{ always() }}
      shell: bash
      run: go clean -fuzzcache

    - name: Normalize non-deterministic cache metadata
      if: ${{ always() }}
      shell: bash
      run: |
        # trim.txt format is Unix epoch seconds as a plain integer
        printf '%d' "$(date +%s)" > "$ERIGON_CI_GOCACHE/trim.txt"
        rm -f "$ERIGON_CI_GOCACHE/testexpire.txt"

    - uses: actions/cache/save@v4
      if: ${{ always() }}
      with:
        path: ${{ env.ERIGON_CI_GOCACHE }}
        key: gocache|${{ env.ERIGON_CI_WORKFLOW }}|${{ github.job }}|${{ env.ERIGON_CI_BUILD_CACHE_EXTRA_KEY && format('{0}|', env.ERIGON_CI_BUILD_CACHE_EXTRA_KEY) || '' }}${{ env.ERIGON_CI_GOVERSION }}|${{ runner.os }}|${{ runner.arch }}|${{ github.head_ref || github.ref_name }}|${{ github.sha }}|${{ github.run_number }}
