---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: erigon
  name: http
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8545
      protocol: TCP
      targetPort: 8545
  selector:
    app: erigon
  type: LoadBalancer