// Code generated by cmd/tools/jsongen. DO NOT EDIT.
// The source of truth is Withdrawal's json and ethjson tags.

package types

import (
	"github.com/erigontech/erigon/rpc/jsonstream"
	"github.com/erigontech/erigon/rpc/jsonstream/ethjson"
)

// MarshalFastJSONTo writes the fields Withdrawal declares, in that order.
func (x *Withdrawal) MarshalFastJSONTo(s *jsonstream.StackStream) error {
	if x == nil {
		s.WriteNil()
		return nil
	}
	s.WriteObjectStart()
	ethjson.Quantity(s, "index", x.Index)
	ethjson.Quantity(s, "validatorIndex", x.Validator)
	ethjson.Data(s, "address", x.Address[:])
	ethjson.Quantity(s, "amount", x.Amount)
	s.WriteObjectEnd()
	return nil
}
