// Copyright 2026 The Erigon Authors
// This file is part of Erigon.
//
// Erigon is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Erigon is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with Erigon. If not, see <http://www.gnu.org/licenses/>.

package types

import (
	"encoding/binary"
	"os"
	"path/filepath"
	"testing"

	"github.com/erigontech/erigon/execution/rlp"
)

// loadHeadersRLP reads a sequence of length-prefixed RLP-encoded headers
// from a testdata file generated by extract_headers (see PR description).
// Format: repeated [u32 LE length][rlp bytes].
func loadHeadersRLP(tb testing.TB, name string) [][]byte {
	tb.Helper()
	path := filepath.Join("testdata", name)
	raw, err := os.ReadFile(path)
	if err != nil {
		tb.Fatalf("read %s: %v", path, err)
	}
	var out [][]byte
	for len(raw) >= 4 {
		n := binary.LittleEndian.Uint32(raw[:4])
		raw = raw[4:]
		if uint32(len(raw)) < n {
			tb.Fatalf("truncated record in %s", path)
		}
		out = append(out, raw[:n])
		raw = raw[n:]
	}
	if len(out) == 0 {
		tb.Fatalf("no headers in %s", path)
	}
	return out
}

// BenchmarkDecodeHeader_PreLondon decodes a single pre-London header (no BaseFee).
// Mainnet epoch 99, ~Sep 2015, Frontier-era headers.
func BenchmarkDecodeHeader_PreLondon(b *testing.B) {
	headers := loadHeadersRLP(b, "headers-mainnet-00099.rlp")
	hRLP := headers[0]
	b.ResetTimer()
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		var h Header
		if err := rlp.DecodeBytes(hRLP, &h); err != nil {
			b.Fatal(err)
		}
	}
}

// BenchmarkDecodeHeader_London decodes a single post-London header (with BaseFee).
// Mainnet epoch 1894, ~Aug 2022, peak pre-merge.
func BenchmarkDecodeHeader_London(b *testing.B) {
	headers := loadHeadersRLP(b, "headers-mainnet-01894.rlp")
	hRLP := headers[0]
	b.ResetTimer()
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		var h Header
		if err := rlp.DecodeBytes(hRLP, &h); err != nil {
			b.Fatal(err)
		}
	}
}

// BenchmarkDecodeHeader_Loop_PreLondon walks 100 pre-London headers per op,
// mirroring the freezeblocks.ForEachHeader pattern: var header in the loop,
// rlp.DecodeBytes(payload, &header), hand to a no-op consumer.
func BenchmarkDecodeHeader_Loop_PreLondon(b *testing.B) {
	headers := loadHeadersRLP(b, "headers-mainnet-00099.rlp")
	b.ResetTimer()
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		for _, hRLP := range headers {
			var h Header
			if err := rlp.DecodeBytes(hRLP, &h); err != nil {
				b.Fatal(err)
			}
			_ = h.ParentHash // prevent dead-code elimination
		}
	}
}

// BenchmarkDecodeHeader_Loop_London walks 100 post-London headers per op.
func BenchmarkDecodeHeader_Loop_London(b *testing.B) {
	headers := loadHeadersRLP(b, "headers-mainnet-01894.rlp")
	b.ResetTimer()
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		for _, hRLP := range headers {
			var h Header
			if err := rlp.DecodeBytes(hRLP, &h); err != nil {
				b.Fatal(err)
			}
			_ = h.ParentHash
		}
	}
}

// BenchmarkEncodeHeader_London round-trips one header through EncodeToBytes.
func BenchmarkEncodeHeader_London(b *testing.B) {
	headers := loadHeadersRLP(b, "headers-mainnet-01894.rlp")
	var h Header
	if err := rlp.DecodeBytes(headers[0], &h); err != nil {
		b.Fatal(err)
	}
	b.ResetTimer()
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		out, err := rlp.EncodeToBytes(&h)
		if err != nil {
			b.Fatal(err)
		}
		_ = out
	}
}

// BenchmarkHeaderHash_Mutable measures Hash() on a fresh (mutable) header —
// hash is recomputed each call. This is the walker-loop pattern.
func BenchmarkHeaderHash_Mutable(b *testing.B) {
	headers := loadHeadersRLP(b, "headers-mainnet-01894.rlp")
	var h Header
	if err := rlp.DecodeBytes(headers[0], &h); err != nil {
		b.Fatal(err)
	}
	h.mutable = true
	b.ResetTimer()
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		_ = h.Hash()
	}
}

// BenchmarkHeaderHash_Memoized measures Hash() with the atomic memoization
// path active (h.mutable == false, first call computes, subsequent calls
// return the cached value).
func BenchmarkHeaderHash_Memoized(b *testing.B) {
	headers := loadHeadersRLP(b, "headers-mainnet-01894.rlp")
	var h Header
	if err := rlp.DecodeBytes(headers[0], &h); err != nil {
		b.Fatal(err)
	}
	h.mutable = false
	_ = h.Hash() // warm the cache
	b.ResetTimer()
	b.ReportAllocs()
	for i := 0; i < b.N; i++ {
		_ = h.Hash()
	}
}
