// Code generated by cmd/ethjsongen. DO NOT EDIT.
// The source of truth is RPCLog's json and ethjson tags.

package types

import (
	"github.com/erigontech/erigon/rpc/jsonstream"
	"github.com/erigontech/erigon/rpc/jsonstream/ethjson"
)

// MarshalFastJSONTo writes the fields RPCLog declares, in that order.
func (x *RPCLog) MarshalFastJSONTo(s *jsonstream.StackStream) error {
	if x == nil {
		s.WriteNil()
		return nil
	}
	s.WriteObjectStart()
	ethjson.Data(s, "address", x.Address[:])
	ethjson.DataList(s, "topics", x.Topics)
	ethjson.Data(s, "data", x.Data[:])
	ethjson.Quantity(s, "blockNumber", x.BlockNumber)
	ethjson.Data(s, "transactionHash", x.TxHash[:])
	ethjson.Quantity(s, "transactionIndex", x.TxIndex)
	ethjson.Data(s, "blockHash", x.BlockHash[:])
	ethjson.Quantity(s, "logIndex", x.Index)
	s.Field("removed").WriteBool(x.Removed)
	ethjson.Quantity(s, "blockTimestamp", x.BlockTimestamp)
	s.WriteObjectEnd()
	return nil
}
