{
 "title": "TurboGeth Prometheus",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "tx_pool_counters",
    "label": "TxPoolCounters",
    "query": "{job=\"geth\"}"
   },
   { "name": "job", "query": "geth" },
   {
    "name": "quantile",
    "query": "0.5, 0.75, 0.95, 0.99, 0.999, 0.9999"
   },
   { "name": "instance", "label": "instance", "query": "trie_resolve_ih" }
  ]
 },
 "panels": [
  { "title": "Trie", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Trie Resolve Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "trie_resolve_ih{quantile=\"$quantile\",instance=\"$instance\"}",
     "legendFormat": "trie/resolve/ih"
    },
    {
     "expr": "trie_resolve_stateful{quantile=\"$quantile\",instance=\"$instance\"}",
     "legendFormat": "trie/resolve/stateful"
    },
    {
     "expr": "trie_resolve_stateless{quantile=\"$quantile\",instance=\"$instance\"}",
     "legendFormat": "trie/resolve/stateless"
    }
   ]
  },
  {
   "title": "IH Insert/Delete RPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(db_ih_insert{instance=\"$instance\"}[1m])",
     "legendFormat": "db/ih/insert"
    },
    {
     "expr": "rate(db_ih_delete{instance=\"$instance\"}[1m])",
     "legendFormat": "db/ih/delete"
    },
    {
     "expr": "rate(db_ih_tombstone_insert{instance=\"$instance\"}[1m])",
     "legendFormat": "db/ih/tombstone_insert"
    },
    {
     "expr": "rate(db_ih_tombstone_delete{instance=\"$instance\"}[1m])",
     "legendFormat": "db/ih/tombstone_delete"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "system_cpu_sysload{instance=\"$instance\"}",
     "legendFormat": "system"
    },
    {
     "expr": "system_cpu_syswait{instance=\"$instance\"}",
     "legendFormat": "iowait"
    },
    {
     "expr": "system_cpu_procload{instance=\"$instance\"}",
     "legendFormat": "geth"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(system_memory_allocs{instance=\"$instance\"}[1m])",
     "legendFormat": "alloc"
    },
    {
     "expr": "system_memory_used{instance=\"$instance\"}",
     "legendFormat": "used"
    },
    {
     "expr": "system_memory_held{instance=\"$instance\"}",
     "legendFormat": "held"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(system_disk_readbytes{instance=\"$instance\"}[1m])",
     "legendFormat": "read"
    },
    {
     "expr": "rate(system_disk_writebytes{instance=\"$instance\"}[1m])",
     "legendFormat": "write"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(p2p_ingress{instance=\"$instance\"}[1m])",
     "legendFormat": "ingress"
    },
    {
     "expr": "rate(p2p_egress{instance=\"$instance\"}[1m])",
     "legendFormat": "egress"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "p2p_peers{instance=\"$instance\"}",
     "legendFormat": "peers"
    },
    {
     "expr": "rate(p2p_dials{instance=\"$instance\"}[1m])",
     "legendFormat": "dials"
    },
    { "expr": "rate(p2p_serves[1m])", "legendFormat": "serves" }
   ]
  },
  { "title": "Blockchain", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Latest header",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "chain_head_header" }
   ]
  },
  {
   "title": "Chain head",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 3, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "chain_head_header{instance=\"$instance\"}",
     "legendFormat": "header"
    },
    {
     "expr": "chain_head_receipt{instance=\"$instance\"}",
     "legendFormat": "receipt"
    },
    {
     "expr": "chain_head_block{instance=\"$instance\"}",
     "legendFormat": "block"
    }
   ]
  },
  {
   "title": "Executable transactions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 24 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "txpool_pending" }
   ]
  },
  {
   "title": "Transaction pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "txpool_pending{instance=\"$instance\"}",
     "legendFormat": "executable"
    },
    {
     "expr": "txpool_queued{instance=\"$instance\"}",
     "legendFormat": "gapped"
    },
    {
     "expr": "txpool_local{instance=\"$instance\"}",
     "legendFormat": "local"
    }
   ]
  },
  {
   "title": "Latest receipt",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "chain_head_receipt" }
   ]
  },
  {
   "title": "Gapped transactions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 26 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "txpool_queued" }
   ]
  },
  {
   "title": "Latest block",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "chain_head_block" }
   ]
  },
  {
   "title": "Local transactions",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "txpool_local" }
   ]
  },
  {
   "title": "Block processing",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "chain_execution{quantile=\"$quantile\",instance=\"$instance\"}",
     "legendFormat": "execution (q=$quantile)"
    },
    {
     "expr": "chain_validation{quantile=\"$quantile\",instance=\"$instance\"}",
     "legendFormat": "validation (q=$quantile)"
    },
    {
     "expr": "chain_write{quantile=\"$quantile\",instance=\"$instance\"}",
     "legendFormat": "commit (q=$quantile)"
    },
    {
     "expr": "chain_account_reads{quantile=\"$quantile\",instance=\"$instance\"}",
     "legendFormat": "account read (q=$quantile)"
    },
    {
     "expr": "chain_account_updates{quantile=\"$quantile\",instance=\"$instance\"}",
     "legendFormat": "account update (q=$quantile)"
    },
    {
     "expr": "chain_account_hashes{quantile=\"$quantile\",instance=\"$instance\"}",
     "legendFormat": "account hashe (q=$quantile)"
    },
    {
     "expr": "chain_account_commits{quantile=\"$quantile\",instance=\"$instance\"}",
     "legendFormat": "account commit (q=$quantile)"
    },
    {
     "expr": "chain_storage_reads{quantile=\"$quantile\",instance=\"$instance\"}",
     "legendFormat": "storage read (q=$quantile)"
    },
    {
     "expr": "chain_storage_updates{quantile=\"$quantile\",instance=\"$instance\"}",
     "legendFormat": "storage update (q=$quantile)"
    },
    {
     "expr": "chain_storage_hashes{quantile=\"$quantile\",instance=\"$instance\"}",
     "legendFormat": "storage hashe (q=$quantile)"
    },
    {
     "expr": "chain_storage_commits{quantile=\"$quantile\",instance=\"$instance\"}",
     "legendFormat": "storage commit (q=$quantile)"
    }
   ]
  },
  {
   "title": "Transaction propagation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(txpool_valid{instance=\"$instance\"}[1m])",
     "legendFormat": "valid"
    },
    {
     "expr": "rate(txpool_invalid{instance=\"$instance\"}[1m])",
     "legendFormat": "invalid"
    },
    {
     "expr": "rate(txpool_underpriced{instance=\"$instance\"}[1m])",
     "legendFormat": "underpriced"
    },
    {
     "expr": "rate(txpool_pending_discard{instance=\"$instance\"}[1m])",
     "legendFormat": "executable discard"
    },
    {
     "expr": "rate(txpool_pending_replace{instance=\"$instance\"}[1m])",
     "legendFormat": "executable replace"
    },
    {
     "expr": "rate(txpool_pending_ratelimit{instance=\"$instance\"}[1m])",
     "legendFormat": "executable ratelimit"
    },
    {
     "expr": "rate(txpool_pending_nofunds{instance=\"$instance\"}[1m])",
     "legendFormat": "executable nofunds"
    },
    {
     "expr": "rate(txpool_queued_discard{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped discard"
    },
    {
     "expr": "rate(txpool_queued_replace{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped replace"
    },
    {
     "expr": "rate(txpool_queued_ratelimit{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped ratelimit"
    },
    {
     "expr": "rate(txpool_queued_nofunds{instance=\"$instance\"}[1m])",
     "legendFormat": "gapped nofunds"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Data rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(eth_db_chaindata_disk_read[1m])",
     "legendFormat": "leveldb read"
    },
    {
     "expr": "rate(eth_db_chaindata_disk_write[1m])",
     "legendFormat": "leveldb write"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_read[1m])",
     "legendFormat": "ancient read"
    },
    {
     "expr": "rate(eth_db_chaindata_ancient_write[1m])",
     "legendFormat": "ancient write"
    }
   ]
  },
  {
   "title": "Session totals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "eth_db_chaindata_disk_read", "legendFormat": "leveldb read" },
    { "expr": "eth_db_chaindata_disk_write", "legendFormat": "leveldb write" },
    { "expr": "eth_db_chaindata_ancient_read", "legendFormat": "ancient read" },
    { "expr": "eth_db_chaindata_ancient_write", "legendFormat": "ancient write" }
   ]
  },
  {
   "title": "Storage size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 49 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "eth_db_chaindata_disk_size", "legendFormat": "leveldb" },
    { "expr": "eth_db_chaindata_ancient_size", "legendFormat": "ancient" }
   ]
  },
  { "title": "Trie Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Clean cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(trie_memcache_clean_read[1m])",
     "legendFormat": "hit"
    },
    {
     "expr": "rate(trie_memcache_clean_write[1m])",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "title": "Dirty cache",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(trie_memcache_gc_size[1m])",
     "legendFormat": "gc"
    },
    {
     "expr": "rate(trie_memcache_flush_size[1m])",
     "legendFormat": "overflow"
    },
    {
     "expr": "rate(trie_memcache_commit_size[1m])",
     "legendFormat": "commit"
    }
   ]
  }
 ]
}