package stagedsync

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
	"sync"

	"github.com/holiman/uint256"

	"github.com/erigontech/erigon/common"
	"github.com/erigontech/erigon/execution/tracing"
	"github.com/erigontech/erigon/execution/types/accounts"
)

// coinbaseTraceEntry captures one balance observation for the traced
// coinbase address at a specific pipeline point.
type coinbaseTraceEntry struct {
	Kind     string
	BlockNum uint64
	TxNum    uint64
	TxIndex  int32
	Balance  uint256.Int
	Reason   tracing.BalanceChangeReason
	Note     string
}

// coinbaseTrace is an unbounded, mutex-guarded growing slice. Dumped on
// trie-root mismatch and on first divergence from the baseline (if any).
type coinbaseTrace struct {
	mu      sync.Mutex
	entries []coinbaseTraceEntry
}

func (t *coinbaseTrace) append(e coinbaseTraceEntry) {
	t.mu.Lock()
	t.entries = append(t.entries, e)
	t.mu.Unlock()
}

func (t *coinbaseTrace) Dump(w io.Writer) (int, error) {
	t.mu.Lock()
	defer t.mu.Unlock()
	for i, e := range t.entries {
		if _, err := fmt.Fprintf(w, "COINBASE_TRACE kind=%s block=%d txNum=%d txIndex=%d bal=%s reason=%d note=%s\n",
			e.Kind, e.BlockNum, e.TxNum, e.TxIndex, e.Balance.String(), e.Reason, e.Note); err != nil {
			return i, err
		}
	}
	return len(t.entries), nil
}

// baselineKey identifies a per-TX ground-truth datapoint.
type baselineKey struct {
	BlockNum uint64
	TxIndex  int32
}

type coinbaseBaseline struct {
	m map[baselineKey]uint256.Int
}

func (b *coinbaseBaseline) lookup(blockNum uint64, txIndex int32) (uint256.Int, bool) {
	v, ok := b.m[baselineKey{blockNum, txIndex}]
	return v, ok
}

func loadCoinbaseBaseline(path string) (*coinbaseBaseline, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	m := make(map[baselineKey]uint256.Int)
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<20), 1<<20)
	line := 0
	for sc.Scan() {
		line++
		s := strings.TrimSpace(sc.Text())
		if s == "" || strings.HasPrefix(s, "#") {
			continue
		}
		fields := strings.Fields(s)
		if len(fields) < 3 {
			return nil, fmt.Errorf("baseline %s:%d expected 3 fields, got %d", path, line, len(fields))
		}
		bn, err := strconv.ParseUint(fields[0], 10, 64)
		if err != nil {
			return nil, fmt.Errorf("baseline %s:%d block_num: %w", path, line, err)
		}
		ti, err := strconv.ParseInt(fields[1], 10, 32)
		if err != nil {
			return nil, fmt.Errorf("baseline %s:%d tx_index: %w", path, line, err)
		}
		var bal uint256.Int
		if err := bal.SetFromDecimal(fields[2]); err != nil {
			return nil, fmt.Errorf("baseline %s:%d balance: %w", path, line, err)
		}
		m[baselineKey{BlockNum: bn, TxIndex: int32(ti)}] = bal
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	return &coinbaseBaseline{m: m}, nil
}

var (
	calcTraceOnce     sync.Once
	calcTraceAddr     *accounts.Address
	calcTraceLog      *coinbaseTrace
	calcBaseline      *coinbaseBaseline
	calcDivergeMu     sync.Mutex
	calcDivergeN      int
	calcDivergeFile   *os.File
	calcBaselineOut   *os.File
	calcBaselineOutMu sync.Mutex
)

func initCalcTrace() {
	calcTraceOnce.Do(func() {
		addrHex := os.Getenv("TRACE_CALC_ADDR")
		if addrHex == "" {
			return
		}
		addr := accounts.InternAddress(common.HexToAddress(addrHex))
		calcTraceAddr = &addr
		calcTraceLog = &coinbaseTrace{}
		if outPath := os.Getenv("COINBASE_BASELINE_OUT"); outPath != "" {
			f, err := os.Create(outPath)
			if err != nil {
				fmt.Printf("COINBASE_BASELINE_OUT: create failed: %v\n", err)
				return
			}
			fmt.Fprintf(f, "# coinbase=%s baseline generated by erigon\n", addrHex)
			calcBaselineOut = f
			fmt.Printf("COINBASE_BASELINE_OUT: writing to %s\n", outPath)
			return
		}
		if baselinePath := os.Getenv("COINBASE_BASELINE"); baselinePath != "" {
			b, err := loadCoinbaseBaseline(baselinePath)
			if err != nil {
				fmt.Printf("COINBASE_BASELINE: load failed: %v\n", err)
				return
			}
			calcBaseline = b
			fmt.Printf("COINBASE_BASELINE: loaded %d entries from %s\n", len(b.m), baselinePath)
		}
	})
}

func traceAddrForCalc() *accounts.Address {
	initCalcTrace()
	return calcTraceAddr
}

func coinbaseTraceLog_() *coinbaseTrace {
	initCalcTrace()
	return calcTraceLog
}

// recordBaselineEntry emits one per-tx coinbase balance line to the
// baseline file. No-op when baseline generation is off.
func recordBaselineEntry(blockNum uint64, txIndex int32, balance uint256.Int) {
	initCalcTrace()
	if calcBaselineOut == nil {
		return
	}
	calcBaselineOutMu.Lock()
	fmt.Fprintf(calcBaselineOut, "%d %d %s\n", blockNum, txIndex, balance.String())
	calcBaselineOutMu.Unlock()
}

// checkCoinbaseBaseline compares observed post-apply balance against loaded
// baseline. Logs every divergence and dumps trace on first hit.
func checkCoinbaseBaseline(blockNum uint64, txIndex int32, observed uint256.Int) bool {
	initCalcTrace()
	if calcBaseline == nil {
		return false
	}
	expected, ok := calcBaseline.lookup(blockNum, txIndex)
	if !ok {
		return false
	}
	if expected.Eq(&observed) {
		return false
	}
	delta := new(uint256.Int).Sub(&expected, &observed)
	calcDivergeMu.Lock()
	defer calcDivergeMu.Unlock()
	calcDivergeN++
	idx := calcDivergeN
	fmt.Printf("COINBASE_DIVERGENCE[%d]: block=%d txIndex=%d expected=%s observed=%s delta=%s\n",
		idx, blockNum, txIndex, expected.String(), observed.String(), delta.String())
	if calcDivergeFile == nil {
		if f, ferr := os.Create("/tmp/coinbase_divergences.log"); ferr == nil {
			calcDivergeFile = f
		}
	}
	if calcDivergeFile != nil {
		fmt.Fprintf(calcDivergeFile, "DIV[%d] block=%d txIndex=%d expected=%s observed=%s delta=%s\n",
			idx, blockNum, txIndex, expected.String(), observed.String(), delta.String())
		calcDivergeFile.Sync()
	}
	return true
}
