name: Save Go module cache
description: Hash and save the Go module download cache

inputs:
  modcache-path:
    description: "Path to the Go module download cache"
    required: true
  tag:
    description: "Tag included in the cache key after go.sum hash"
    required: true
  restored-key:
    description: "The cache key that was restored (from actions/cache/restore output cache-matched-key). If the save key matches, the save is skipped."
    required: true

runs:
  using: composite
  steps:
    - name: Show module cache size
      if: ${{ always() }}
      shell: bash
      run: du -hs '${{ inputs.modcache-path }}' '${{ inputs.modcache-path }}/cache/download' || true

    - name: Hash module cache contents
      id: mod-hash
      if: ${{ always() }}
      shell: bash
      run: |
        hash=$(cd '${{ inputs.modcache-path }}/cache/download' && find . -type d -name '*@*' | sort | sha256sum | cut -d' ' -f1)
        echo "hash=$hash" >> "$GITHUB_OUTPUT"
        tag='${{ inputs.tag }}'
        if [[ -n "$tag" ]]; then
          save_key='gomodcache|${{ runner.os }}|${{ hashFiles('go.sum') }}|'"${tag}|${hash}"
        else
          save_key='gomodcache|${{ runner.os }}|${{ hashFiles('go.sum') }}|'"${hash}"
        fi
        echo "save-key=$save_key" >> "$GITHUB_OUTPUT"

    - name: Save Go module cache
      if: ${{ always() && steps.mod-hash.outputs.save-key != inputs.restored-key }}
      uses: actions/cache/save@v4
      with:
        path: ${{ inputs.modcache-path }}/cache/download
        key: ${{ steps.mod-hash.outputs.save-key }}
