name: Docker Image CI

on:
  push:
    branches: ["eip_4844"]
  pull_request:
    branches: ["eip_4844"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}

        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag racytech/erigon:$(date +%s)

      - name: Docker Push
        run: docker push ${{secrets.DOCKER_USER}}/erigon
