name: "IS build/publish docker image"

on:
  workflow_dispatch: {}

  push:
    branches:
      - "develop"
      - "ci/cloudrun"
    tags:
      - "v*"
    paths-ignore:
      - "**/README.md"

  pull_request:
    branches: [develop]
    paths-ignore:
      - "**/README.md"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publishing:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GCP Registry
        uses: docker/login-action@v2
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GCP_DOCKER_KEY }}

      # - name: Login to Github Registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ghcr.io
      #     username: ${{ secrets.GH_PKG_LOGIN }}
      #     password: ${{ secrets.GH_PKG_TOKEN }}

      - name: Checkout template repo
        uses: actions/checkout@v3

      - name: Building base Rust/DFX image
        uses: docker/build-push-action@v4
        with:
          # push: ${{ (github.event_name != 'pull_request' && github.ref == 'refs/heads/main') ||  github.ref_type == 'tag' }}
          push: true
          context: .
          file: ./Dockerfile.cloudrun
          tags: |
            us-central1-docker.pkg.dev/dfx-server/dfx-containers/erigon-dev:latest
  
          # tags: |
          #   ghcr.io/${{ github.repository_owner }}/ic-dev-base:latest
          #   ghcr.io/${{ github.repository_owner }}/ic-dev-base:${{ env.BUILD_TAG }}
          #   us-central1-docker.pkg.dev/dfx-server/dfx-server/dfx-containers/erigon-dev:latest

      # Condition to use latest tag
      # output-image-tag-latest: ${{ github.ref_type == 'branch' && github.ref == 'refs/heads/develop' }}
      # output-image-tag-latest: ${{ github.ref_type == 'branch' }}
      # Condition to publish docker image
      # push-image: ${{ (github.event_name != 'pull_request' && github.ref == 'refs/heads/develop') ||  github.ref_type == 'tag' }}

