name: Nightly - RPC Batch Compare

on:
  schedule:
    - cron: '0 23 * * *'
  workflow_dispatch:


jobs:
  run-rpc-batch-compare:
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        include:
          - name: bali
            legacy: "https://rpc.zkevm-internal.com"
            erigon: "https://rpc.internal.zkevm-rpc.com"
          - name: integration8
            legacy: "http://34.175.214.161:18505"
            erigon: "http://34.175.214.161:18124"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.25'
          
      - name: Set Go toolchain
        run: go env -w GOTOOLCHAIN=go1.25.0+auto

      - name: Run RPC Batch Compare
        run: go run ./zk/debug_tools/rpc-batch-compare -erigon="${{ matrix.erigon }}" -legacy="${{ matrix.legacy }}" -skip=100 -offset=1
