name: QA - Sync from scratch

on:
  schedule:
    - cron: '0 0 * * 0'  # Run on Sunday at 00:00 AM UTC
  workflow_dispatch:     # Run manually

jobs:
  sync-from-scratch-test:
    runs-on: self-hosted
    timeout-minutes: 800
    strategy:
      fail-fast: false
      matrix:
        chain: [ sepolia, amoy ]  # Chain name as specified on the erigon command line
    env:
      ERIGON_DATA_DIR: ${{ github.workspace }}/erigon_data
      ERIGON_QA_PATH: /home/qarunner/erigon-qa
      TRACKING_TIME_SECONDS: 7200 # 2 hours
      TOTAL_TIME_SECONDS: 43200 # 12 hours
      CHAIN: ${{ matrix.chain }}

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Clean Erigon Build & Data Directories
      run: |
        make clean
        rm -rf $ERIGON_DATA_DIR

    - name: Build Erigon
      run: |
        make erigon
      working-directory: ${{ github.workspace }}

    - name: Pause the Erigon instance dedicated to db maintenance
      run: |
        python3 $ERIGON_QA_PATH/test_system/db-producer/pause_production.py || true

    - name: Run Erigon and monitor chain sync
      id: test_step
      run: |
        set +e # Disable exit on error
             
        # Run Erigon, wait sync and check ability to maintain sync
        python3 $ERIGON_QA_PATH/test_system/qa-tests/tip-tracking/run_and_check_tip_tracking.py \
          ${{ github.workspace }}/build/bin $ERIGON_DATA_DIR $TRACKING_TIME_SECONDS $TOTAL_TIME_SECONDS Erigon3 $CHAIN
        
        # Capture monitoring script exit status
        test_exit_status=$?
        
        # Save the subsection reached status
        echo "::set-output name=test_executed::true"
        
        # Clean up Erigon process if it's still running
        if kill -0 $ERIGON_PID 2> /dev/null; then
          echo "Terminating Erigon"
          kill $ERIGON_PID
          wait $ERIGON_PID
        fi
        
        # Check test runner script exit status
        if [ $test_exit_status -eq 0 ]; then
          echo "Tests completed successfully"
          echo "TEST_RESULT=success" >> "$GITHUB_OUTPUT"
        else
          echo "Error detected during tests"
          echo "TEST_RESULT=failure" >> "$GITHUB_OUTPUT"
        fi

    - name: Clean up Erigon data directory
      if: always()
      run: |
        rm -rf $ERIGON_DATA_DIR

    - name: Resume the Erigon instance dedicated to db maintenance
      run: |
        python3 $ERIGON_QA_PATH/test_system/db-producer/resume_production.py || true

    - name: Save test results
      if: steps.test_step.outputs.test_executed == 'true'
      env:
        TEST_RESULT: ${{ steps.test_step.outputs.TEST_RESULT }}
      run: |
        python3 $ERIGON_QA_PATH/test_system/qa-tests/uploads/upload_test_results.py \
          --repo erigon \
          --commit $(git rev-parse HEAD) \
          --branch ${{ github.ref_name }} \
          --test_name sync-from-scratch \
          --chain $CHAIN \
          --runner ${{ runner.name }} \
          --outcome $TEST_RESULT \
          --result_file ${{ github.workspace }}/result-$CHAIN.json

    - name: Upload test results
      if: steps.test_step.outputs.test_executed == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: ${{ github.workspace }}/result-${{ env.CHAIN }}.json

    - name: Action for Success
      if: steps.test_step.outputs.TEST_RESULT == 'success'
      run: echo "::notice::Tests completed successfully"

    - name: Action for Not Success
      if: steps.test_step.outputs.TEST_RESULT != 'success'
      run: |
        echo "::error::Error detected during tests"
        exit 1