name: Windows downloader tests

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
    branches:
      - '**'
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  workflow_dispatch:

jobs:
  win-downloader:
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Tests now run in the 'All tests' workflow"
